In [1]:
import pandas as pd
import os

In [2]:
usuario = os.getlogin()

In [3]:
base = pd.read_excel(fr"C:\Users\{usuario}\Downloads\reporte\reporte-new\base\resultados_encuesta_imss_bienestar (1).xlsx")
clues = pd.read_parquet(fr"C:\Users\{usuario}\IMSS-BIENESTAR\División de Procesamiento de información - Repositorio de Datos\CLUES\clues.parquet")

In [4]:
base = base.drop(columns=['ID','Fecha'])

In [5]:
base.columns

Index(['Perfil', 'Entidad', 'Hospital', 'CLUES', 'Region', 'Prueba',
       '¿Cuántos años cumplidos tiene?', 'Sexo',
       '¿Cuál es su formación principal?',
       '¿Tiene estudios de posgrado en administración o gestión de servicios de salud?',
       '¿Cuánto tiempo lleva como coordinador(a) de esta región?',
       '¿Cuál es su tipo de nombramiento en el cargo actual?',
       '¿Su plaza a qué institución pertenece?',
       'En general, ¿cómo calificaría la situación actual de los hospitales de su región?',
       'Comparada con antes de que los hospitales de su región pasaran a IMSS Bienestar (enero de 2024), la situación general de los hospitales de su región...',
       'En los próximos 12 meses, ¿espera que la situación de los hospitales de su región...',
       '¿Hay algún servicio o área de su hospital que hoy esté cerrado o funcionando de forma parcial?',
       'Compare cada aspecto de la situación de los hospitales de su región con antes de que pasaran a IMSS Bienestar (enero de 2024).',
       'Actualmente, ¿cuáles de estos aspectos son un problema grave en su hospital? (Seleccione solo 3)',
       'Antes de que su hospital pasara a IMSS Bienestar (enero de 2024), ¿cuáles de estos aspectos eran un problema grave en su hospital? (Seleccione solo 3)',
       '¿Cómo describiría el almacén de su hospital para medicamentos e insumos?',
       'Actualmente, ¿cuáles de estos aspectos son un problema grave en los hospitales de su región? (Seleccione solo 3)',
       'D1a. Si respondió «Sí», ¿de cuánto era aproximadamente al mes?',
       '¿Qué tan necesario considera contar con un fondo rotatorio para la operación de su hospital?',
       'Antes de que los hospitales de su región pasaran a IMSS Bienestar (enero de 2024), ¿cuáles de estos aspectos eran un problema grave en la región? (Seleccione solo 3)',
       'Al día de hoy, ¿cuántas personas integran la plantilla total de su hospital?',
       'Del total anterior, ¿cuántas personas son personal médico (médicos generales, especialistas y residentes)?',
       'Del total, ¿cuántas personas se dedican a la atención al usuario y al trato digno (trabajo social, módulo de atención y orientación, gestor de calidad u otras áreas afines)?',
       'Para cada tipo de personal, ¿cuántas personas necesitaría contratar como mínimo indispensable en los próximos 3 meses?',
       'Si anotó médicos especialistas en la pregunta anterior, ¿de qué especialidades y cuántos?',
       '¿Qué tipo de aire acondicionado tiene su hospital?',
       '¿Su hospital cuenta con chiller (enfriador de agua para el sistema central)?',
       '¿Cuántos equipos de aire acondicionado individuales tiene instalados su hospital?',
       'De ellos, ¿cuántos son minisplits?',
       'De esos equipos individuales, ¿cuántos no funcionan hoy?',
       '¿Cuántos elevadores tiene su hospital?',
       'De ellos, ¿cuántos no funcionan hoy?',
       '¿Cuántas ambulancias tiene asignadas su hospital?',
       'De ese total, ¿cuántas se encuentran actualmente en funcionamiento, es decir, en condiciones de dar servicio hoy?',
       'De las ambulancias que no funcionan, ¿cuál es la causa principal? (Marque las que apliquen)',
       '¿Quién opera las ambulancias? (Marque según las que apliquen)',
       '¿Las ambulancias son propias o se prestan mediante un servicio? (Marque según las que apliquen)',
       '¿Con cuántas personas cuenta para operar las ambulancias (operadores, paramédicos o técnicos en urgencias médicas)?',
       '¿Qué necesita su hospital en materia de ambulancias? (Marque 3 máximo)',
       'Describa brevemente la principal necesidad o problema en el traslado de pacientes de su hospital:',
       'En una frase, ¿qué aspecto de IMSS Bienestar considera más positivo para su región?',
       'En una frase, ¿qué aspecto de IMSS Bienestar considera que más necesita mejorar?',
       'H1. Si pudiera pedir una sola acción al nivel central para mejorar su región en los próximos 6 meses, ¿cuál sería?',
       'Especifique', 'Otro (especifique)', 'Otro: cantidad'],
      dtype='object')

In [9]:
conteo_perfil = base ['En general, ¿cómo calificaría la situación actual de los hospitales de su región?'].unique()
conteo_perfil

array(['Buena', 'Mala', 'Regular'], dtype=object)

In [7]:
base

,Perfil,Entidad,Hospital,CLUES,Region,Prueba,¿Cuántos años cumplidos tiene?,Sexo,¿Cuál es su formación principal?,¿Tiene estudios de posgrado en administración o gestión de servicios de salud?,...,¿Las ambulancias son propias o se prestan mediante un servicio? (Marque según las que apliquen),"¿Con cuántas personas cuenta para operar las ambulancias (operadores, paramédicos o técnicos en urgencias médicas)?",¿Qué necesita su hospital en materia de ambulancias? (Marque 3 máximo),Describa brevemente la principal necesidad o problema en el traslado de pacientes de su hospital:,"En una frase, ¿qué aspecto de IMSS Bienestar considera más positivo para su región?","En una frase, ¿qué aspecto de IMSS Bienestar considera que más necesita mejorar?","H1. Si pudiera pedir una sola acción al nivel central para mejorar su región en los próximos 6 meses, ¿cuál sería?",Especifique,Otro (especifique),Otro: cantidad
0,Director de hospital,Puebla,HOSPITAL GENERAL TLATLAUQUITEPEC,PLIMB005070,Teziutlan,No,42,Hombre,"Médico general, sin especialidad","Sí, concluidos",...,Propias,5.0,Más unidades; Personal operativo,SE REQUIERE: 1 INCUBADORA DE TRASLADO PARA NEO...,LA ESTABILIDAD LABORAL QUE SE LE BRINBDÓ EN LA...,MANTENIMIENTOS PREVENTIVOS / CORRECTIVOS PARA ...,MANTENIMIENTOS PREVENTIVOS / CORRECTIVOS AL EQ...,NaN,NaN,NaN
1,Director de hospital,Quintana Roo,HOSPITAL GENERAL DE CANCÚN DR. JESÚS KUMATE RO...,QRIMB001973,Cancún,No,40,Hombre,Otra especialidad médica,No,...,Propias,1.0,Personal operativo; Capacitación; Equipamiento...,Falta de personal para operar las ambulancias....,Se requiere reforzar la presencia de personal ...,"Coordinación, comunicación y continuidad de pr...","Garantizar abasto de insumos, medicamentos y e...",Cirujano Cardio torácico y Congenitos,Endoscopista,2.0
2,Director de hospital,Quintana Roo,HOSPITAL GENERAL DE FELIPE CARRILLO PUERTO,QRIMB000025,Felipe Carrillo Puerto,No,37,Hombre,"Médico general, sin especialidad",No,...,"Propias; Prestadas o en comodato (por ejemplo,...",6.0,Reparación o mantenimiento; Combustible o pres...,"Falta de especialista, tenemos que trasladar",Mejora en mantenimiento y viveres,Mayor contratación y mejora en aplicar sanciones,Contratación de personal,Confianza,NaN,NaN
3,Director de hospital,Guerrero,HOSPITAL GENERAL OMETEPEC,GRIMB005163,Ometepec,No,43,Hombre,"Médico general, sin especialidad","Sí, en curso",...,Propias,5.0,Más unidades; Equipamiento médico; Capacitación,Espacios para embarazadas con prematuros,Universalizacion de los servicios,Equipamiento medico e infraestructura,Equipamiento y personal,NaN,Radiologo,11.0
4,Director de hospital,Guerrero,HOSPITAL DE LA MADRE Y EL NIÑO INDIGENA GUERRE...,GRIMB008890,Tlapa,No,43,Hombre,Anestesiología,"Sí, concluidos",...,Propias,1.0,Personal operativo; Capacitación; Reparación o...,Personal disponible,Gestión directiva,Rapidez al solucionar y dar respuesta,Presupuesto propio,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,Director de hospital,Puebla,HOSPITAL COMUNITARIO DR. MIGUEL ANGEL COBOS MARIN,PLIMB006004,Tepexi,No,56,Mujer,"Médico general, sin especialidad","Sí, concluidos",...,Propias,4.0,Reparación o mantenimiento; Personal operativo...,Falta de personal medico y de enfermeria ya qu...,Contratación de personal especialista ya que a...,Surtimiento de material de curacion en base a ...,Equipo de rayos x,NaN,NaN,NaN
127,Director de hospital,Puebla,HOSPITAL INTEGRAL DE XICOTEPEC,PLIMB005601,Huauchinango,No,54,Mujer,"Médico general, sin especialidad","Sí, concluidos",...,Propias,2.0,Más unidades; Equipamiento médico; Personal op...,"Aceptación de pacientes en otras unidades, dis...",Contratación dw Especialistas,"Seguimiento, intervención y resolución pronta ...",INSUMOS,NaN,"Trabajo Social, Quimicofarmavobiologo",4.0
128,Director de hospital,Puebla,HOSPITAL COMUNITARIO ZACAPALA,PLIMB007095,Tepexi,No,38,Mujer,"Médico general, sin especialidad","Sí, concluidos",...,Propias,0.0,Reparación o mantenimiento; Equipamiento médic...,"HOSPITALES RESEPTORES, PERSONAL CHOFERES, MANT...",falta la culminación de transición por complet...,en la evaluación del personal,"plantillas completas, insumos, medicamentos, p...",NaN,NaN,NaN
129,Director de hospital,Puebla,HOSPITAL COMUNITARIO IXTACAMAXTITLAN,PLIMB001285,Zacatlan,No,39,Mujer,"Médico general, sin especialidad","Sí, concluidos",...,Propias,2.0,Otra (especifique),Sustitución de la actual con sus aditamentos y...,Atención integral del paciente,Mantenimiento de equipo e insumos que en base ...,Mantenimiento y sustitución de equipo medico,NaN,NaN,NaN
130,Director de hospital,Puebla,HOSPITAL GENERAL DE LA ZONA NORTE BICENTENARI...,PLIMB005910,Puebla,No,70,Hombre,Cirugía general,No,...,Propias,15.0,Reparación o mantenimiento; Más unidades,Falta de recurso humano (médico de traslado),La buena gestión realizada,La gestión en abasto de medicamentos y materia...,Mejorar el abastecimiento de medicamentos y ma...,NaN,NaN,NaN

In [8]:
break

SyntaxError: 'break' outside loop (668683560.py, line 1)

In [ ]:
base_an.columns

Index(['fecha_registro', 'tipo_registro', 'entidad', 'usuario_nombre',
       'usuario_email', 'clues_imb', 'nombre_de_la_unidad',
       'categoria_gerencial_ampliada', 'internet', 'consultorios_habilitados',
       'consultorio', 'pregunta', 'valor', 'turno'],
      dtype='object')

In [ ]:
col = ["clues_imb"]
base = base[col]

In [ ]:
clues.columns

Index(['clues_imb', 'clues_ssa_y_sme', 'categoria_gerencial_uas',
       'categoria_gerencial', 'categoria_gerencial_ampliada',
       'clave_de_la_entidad', 'entidad', 'clave_del_municipio', 'municipio',
       'localidad', 'clave_de_la_localidad', 'nombre_de_la_unidad',
       'nombre_comercial', 'estatus_de_operacion', 'nivel_atencion',
       'clave_de_tipologia', 'nombre_de_tipologia', 'clave_de_subtipologia',
       'nombre_de_subtipologia', 'estrato_unidad', 'cve_ro', 'nombre_region',
       'latitud', 'longitud', 'organ_ro', 'tipo_hbc'],
      dtype='object')

In [ ]:
base = base.merge(
    clues[["clues_imb", "entidad",'nombre_de_la_unidad']],
    on="clues_imb",
    how="left"
)

In [ ]:
colum =['clues_imb', 'entidad','consultorios_habilitados','consultorio','pregunta','nombre_de_la_unidad',]
base_an = base_an[colum]

In [ ]:
b = pd.read_excel(fr"C:\Users\{usuario}\Downloads\nuevo-f\formulario-ang\bases\UM_IMB_SUS.xlsx",sheet_name="Hoja2")

In [ ]:
b = b.drop(index=[0, 2, 5,3,1])

In [ ]:
b = b.drop(columns=['Unnamed: 1'])

In [ ]:
b = b.rename(columns={
   'CLUES' : 'preguntas',
})

In [ ]:
b.columns

Index(['preguntas'], dtype='object')

In [ ]:
base

,clues_imb,entidad,nombre_de_la_unidad
0,BCIMB000051,BAJA CALIFORNIA,COLONIA LOMA LINDA
1,BCIMB000092,BAJA CALIFORNIA,FRACCIONAMIENTO MAR
2,BCIMB000162,BAJA CALIFORNIA,ISLA DE CEDROS
3,BCIMB000186,BAJA CALIFORNIA,LA MISIÓN
4,BCIMB000191,BAJA CALIFORNIA,REAL DEL CASTILLO
...,...,...,...
2822,GRIMB010244,GUERRERO,CENTRO DE SALUD CON SERVICIOS AMPLIADOS DE CHI...
2823,GRIMB010256,GUERRERO,CENTRO DE SALUD CON SERVICIOS AMPLIADOS DE HUI...
2824,GRIMB010565,GUERRERO,CENTRO DE SALUD CON SERVICIOS AMPLIADOS MARQUELIA
2825,SRIMB001071,SONORA,CENTRO DE SALUD RURAL MIGUEL ALEMÁN
2826,TCIMB000704,TABASCO,CESSA VICENTE GUERRERO

In [ ]:
base_an.head()

,clues_imb,entidad,consultorios_habilitados,consultorio,pregunta,nombre_de_la_unidad
0,CCIMB000085,CAMPECHE,7.0,NaN,internet,CENTRO DE SALUD DR. WILBERTH ESCALANTE
1,HGIMB000530,HIDALGO,2.0,NaN,internet,PROGRESO EL DE ATOTONILCO DE TULA
2,BCIMB000092,BAJA CALIFORNIA,NaN,1.0,equipo_de_computo_consultorio_1,FRACCIONAMIENTO MAR
3,BCIMB000092,BAJA CALIFORNIA,NaN,2.0,equipo_de_computo_consultorio_2,FRACCIONAMIENTO MAR
4,BCIMB000092,BAJA CALIFORNIA,NaN,1.0,banco_de_altura_consultorio_1,FRACCIONAMIENTO MAR

In [ ]:
base_an = base_an[
    ~base_an["pregunta"].str.contains("internet|turno_consultorio|consultorios_habilitados", case=False, na=False)
]

In [ ]:
base_conteo =base["clues_imb"].unique()
base_conteo

array(['BCIMB000051', 'BCIMB000092', 'BCIMB000162', ..., 'GRIMB010565',
       'SRIMB001071', 'TCIMB000704'], shape=(2191,), dtype=object)

In [ ]:
total_unidades = base["clues_imb"].nunique()

respondieron = base_an["clues_imb"].nunique()

sin_responder = total_unidades - respondieron

avance_general = round(respondieron / total_unidades * 100, 1)

## tablas

In [ ]:
# TABLA 1 - AVANCE POR ENTIDAD

# Unidades esperadas
esperadas = (
    base
    .groupby("entidad")
    .size()
    .reset_index(name="esperadas")
)

# Unidades que respondieron
contestadas = (
    base_an[["entidad","clues_imb"]]
    .drop_duplicates()
    .groupby("entidad")
    .size()
    .reset_index(name="respondieron")
)

tabla_entidades = (
    esperadas
    .merge(contestadas,
           on="entidad",
           how="left")
)

tabla_entidades["respondieron"] = (
    tabla_entidades["respondieron"]
    .fillna(0)
    .astype(int)
)

tabla_entidades["porcentaje"] = (
    tabla_entidades["respondieron"]
    / tabla_entidades["esperadas"]
    *100
).round(1)

tabla_entidades = tabla_entidades.sort_values(
    "porcentaje",
    ascending=False
)

In [ ]:
tabla_entidades

                            entidad  esperadas  respondieron  porcentaje
3                           CHIAPAS         25            23        92.0
15                  SAN LUIS POTOSI         33            27        81.8
21                        ZACATECAS         23            18        78.3
8                            MEXICO        306           220        71.9
6                          GUERRERO        592           418        70.6
7                           HIDALGO         34            24        70.6
9               MICHOACAN DE OCAMPO         43            27        62.8
10                          MORELOS         58            35        60.3
14                     QUINTANA ROO        165            92        55.8
16                          SINALOA        120            66        55.0
11                          NAYARIT         95            46        48.4
5                            COLIMA         97            42        43.3
20  VERACRUZ DE IGNACIO DE LA LLAVE        128            49        38.3
19                       TAMAULIPAS        210            80        38.1
12                           OAXACA         86            31        36.0
1               BAJA CALIFORNIA SUR         70            25        35.7
2                          CAMPECHE         45            16        35.6
18                          TABASCO        169            53        31.4
0                   BAJA CALIFORNIA         92             7         7.6
13                           PUEBLA         16             1         6.2
17                           SONORA        149             2         1.3
4                  CIUDAD DE MEXICO        271             0         0.0

In [ ]:
base_an

,clues_imb,entidad,consultorios_habilitados,consultorio,pregunta,nombre_de_la_unidad
2,BCIMB000092,BAJA CALIFORNIA,NaN,1.0,equipo_de_computo_consultorio_1,FRACCIONAMIENTO MAR
3,BCIMB000092,BAJA CALIFORNIA,NaN,2.0,equipo_de_computo_consultorio_2,FRACCIONAMIENTO MAR
4,BCIMB000092,BAJA CALIFORNIA,NaN,1.0,banco_de_altura_consultorio_1,FRACCIONAMIENTO MAR
5,BCIMB000092,BAJA CALIFORNIA,NaN,2.0,banco_de_altura_consultorio_2,FRACCIONAMIENTO MAR
12,BCIMB000536,BAJA CALIFORNIA,NaN,1.0,equipo_de_computo_consultorio_1,DURANGO
...,...,...,...,...,...,...
87231,MCIMB002150,MEXICO,NaN,1.0,tijera_recta_consultorio_1,HÉROES DE GRANADITAS
87232,MCIMB002150,MEXICO,NaN,1.0,torundera_con_tapa_de_acero_inoxidable_consult...,HÉROES DE GRANADITAS
87233,MCIMB002150,MEXICO,NaN,2.0,torundera_con_tapa_de_acero_inoxidable_consult...,HÉROES DE GRANADITAS
87234,MCIMB002150,MEXICO,NaN,1.0,vaso_contenedor__de_vacunas_consultorio_1,HÉROES DE GRANADITAS
87235,MCIMB002150,MEXICO,NaN,2.0,vaso_contenedor__de_vacunas_consultorio_2,HÉROES DE GRANADITAS

In [ ]:
base_an = base_an.drop_duplicates()

In [ ]:
# TABLA NUEVA - FALTANTES POR ESTADOS

# Universo esperado de unidades (CLUES) por estado
esperadas_estado = (
    base[["entidad", "clues_imb", "nombre_de_la_unidad"]]
    .dropna(subset=["entidad", "clues_imb"])
    .drop_duplicates()
)

# CLUES que si respondieron (al menos una pregunta)
respondidas_estado = (
    base_an[["clues_imb"]]
    .dropna(subset=["clues_imb"])
    .drop_duplicates()
    .merge(
        base[["clues_imb", "entidad"]].drop_duplicates(),
        on="clues_imb",
        how="left"
    )
    .dropna(subset=["entidad"])
    .drop_duplicates()
)

clues_sin_consultorios_estado = (
    consultorios_habilitados_por_unidad
    .loc[consultorios_habilitados_por_unidad["consultorios_habilitados"] == 0, ["entidad", "clues_imb"]]
    .dropna(subset=["entidad", "clues_imb"])
    .drop_duplicates()
)

# Si no hay consultorios habilitados, la unidad se considera atendida para faltantes.
respondidas_estado = (
    pd.concat(
        [respondidas_estado[["entidad", "clues_imb"]], clues_sin_consultorios_estado],
        ignore_index=True,
    )
    .drop_duplicates()
)

# Anti-join: faltantes = esperadas - respondidas
faltantes_por_estados = (
    esperadas_estado
    .merge(
        respondidas_estado[["entidad", "clues_imb"]],
        on=["entidad", "clues_imb"],
        how="left",
        indicator=True
    )
    .query('_merge == "left_only"')
    .drop(columns=["_merge"])
    .sort_values(["entidad", "clues_imb"])
    .reset_index(drop=True)
)

# Resumen de CLUES faltantes por estado
tabla_faltantes_por_estados = (
    faltantes_por_estados
    .groupby("entidad", as_index=False)
    .agg(clues_faltantes=("clues_imb", "nunique"))
    .sort_values("clues_faltantes", ascending=False)
)

display(tabla_faltantes_por_estados)
display(faltantes_por_estados.head(100))

                            entidad  clues_faltantes
4                  CIUDAD DE MEXICO              192
6                          GUERRERO              174
13                           SONORA              121
14                          TABASCO               79
15                       TAMAULIPAS               70
0                   BAJA CALIFORNIA               66
11                     QUINTANA ROO               41
1               BAJA CALIFORNIA SUR               26
16  VERACRUZ DE IGNACIO DE LA LLAVE               26
9                            OAXACA               22
5                            COLIMA               18
10                           PUEBLA               15
2                          CAMPECHE               15
7                           MORELOS               11
8                           NAYARIT               10
3                           CHIAPAS                1
12                  SAN LUIS POTOSI                1
17                        ZACATECAS                1

            entidad    clues_imb                          nombre_de_la_unidad
0   BAJA CALIFORNIA  BCIMB000051                           COLONIA LOMA LINDA
1   BAJA CALIFORNIA  BCIMB000063                            COLONIA POPULAR 2
2   BAJA CALIFORNIA  BCIMB000075                           COLONIA POPULAR 89
3   BAJA CALIFORNIA  BCIMB000104                                 COL. JALISCO
4   BAJA CALIFORNIA  BCIMB000116                          COL. LOMITAS INDECO
..              ...          ...                                          ...
95         CAMPECHE  CCIMB000126                          CENTRO DE SALUD IMÍ
96         CAMPECHE  CCIMB000464  CENTRO DE SALUD VICENTE GUERRERO (ITURBIDE)
97         CAMPECHE  CCIMB000476           CENTRO DE SALUD SAN ANTONIO YAXCHE
98         CAMPECHE  CCIMB000481                         CENTRO DE SALUD UKUM
99         CAMPECHE  CCIMB000493                      CENTRO DE SALUD XCAN HA

[100 rows x 3 columns]

In [ ]:
# TABLA 2 - COMPLETITUD POR UNIDAD

# Número de preguntas del formulario
n_preguntas = len(b)

# Número de consultorios por unidad (prioriza consultorios_habilitados).
consultorios_capturados = (
    base_an
    .groupby(["clues_imb", "entidad", "nombre_de_la_unidad"], as_index=False)
    ["consultorio"]
    .max()
    .rename(columns={"consultorio": "consultorios_capturados"})
)
consultorios_capturados["consultorios_capturados"] = pd.to_numeric(
    consultorios_capturados["consultorios_capturados"], errors="coerce"
)

consultorios = (
    base[["clues_imb", "entidad", "nombre_de_la_unidad"]]
    .dropna(subset=["clues_imb", "entidad"])
    .drop_duplicates()
    .merge(
        consultorios_habilitados_por_unidad,
        on=["clues_imb", "entidad", "nombre_de_la_unidad"],
        how="left"
    )
    .merge(
        consultorios_capturados,
        on=["clues_imb", "entidad", "nombre_de_la_unidad"],
        how="left"
    )
)

consultorios["consultorios"] = (
    consultorios["consultorios_habilitados"]
    .combine_first(consultorios["consultorios_capturados"])
    .fillna(0)
)

consultorios = consultorios[["clues_imb", "entidad", "nombre_de_la_unidad", "consultorios"]]

# Preguntas respondidas
respondidas = (
    base_an
    .groupby(["clues_imb", "entidad", "nombre_de_la_unidad"])
    .size()
    .reset_index(name="respondidas")
)

tabla_unidades = consultorios.merge(
    respondidas,
    on=["clues_imb", "entidad", "nombre_de_la_unidad"],
    how="left"
)

tabla_unidades["respondidas"] = tabla_unidades["respondidas"].fillna(0)

tabla_unidades["esperadas"] = (
    tabla_unidades["consultorios"]
    * n_preguntas
)

tabla_unidades["porcentaje"] = 0.0
mask_esperadas_positivas = tabla_unidades["esperadas"] > 0
tabla_unidades.loc[mask_esperadas_positivas, "porcentaje"] = (
    tabla_unidades.loc[mask_esperadas_positivas, "respondidas"]
    / tabla_unidades.loc[mask_esperadas_positivas, "esperadas"]
    * 100
)
tabla_unidades["porcentaje"] = tabla_unidades["porcentaje"].clip(lower=0, upper=100).round(1)

# Regla de negocio: si no hay consultorios habilitados, el llenado es 100%.
tabla_unidades.loc[tabla_unidades["consultorios"] == 0, "porcentaje"] = 100.0

tabla_unidades = (
    tabla_unidades
    .rename(columns={"clues_imb":"clues"})
    .sort_values("porcentaje")
)

In [ ]:
tabla_unidades.head()

,clues,entidad,nombre_de_la_unidad,consultorios,respondidas,esperadas,porcentaje
863,GRIMB000263,GUERRERO,U-03 COL. PAROTAS,2.0,0.0,88.0,0.0
862,GRIMB000251,GUERRERO,U-03 COL. JARDIN AZTECA,2.0,0.0,88.0,0.0
307,NTIMB001321,NAYARIT,"TEPIC, COL. VALLE DE MATATIPAC",3.0,0.0,132.0,0.0
309,NTIMB001350,NAYARIT,TEPIC (JUAN ESCUTIA),7.0,0.0,308.0,0.0
296,NTIMB000435,NAYARIT,COFRADÍA DE CHOCOLÓN,1.0,0.0,44.0,0.0

In [ ]:
b.head()

                              preguntas
4                     Equipo de cómputo
6                       Banco de altura
7                       Banco giratorio
8  Báscula electrónica  con estadímetro
9        Báscula pesabebés electrónica

In [ ]:
# LISTAS PARA JINJA2
entidades = tabla_entidades.to_dict(orient="records")
unidades = tabla_unidades.to_dict(orient="records")

In [ ]:
tabla_entidades = (
    tabla_unidades
    .groupby("entidad", as_index=False)
    .agg(
        consultorios=("consultorios", "sum"),
        respondidas=("respondidas", "sum"),
        esperadas=("esperadas", "sum"),
        unidades=("clues", "count")
    )
)

tabla_entidades["porcentaje"] = 0.0
mask_esperadas_entidad = tabla_entidades["esperadas"] > 0
tabla_entidades.loc[mask_esperadas_entidad, "porcentaje"] = (
    tabla_entidades.loc[mask_esperadas_entidad, "respondidas"]
    / tabla_entidades.loc[mask_esperadas_entidad, "esperadas"]
    * 100
)
tabla_entidades["porcentaje"] = tabla_entidades["porcentaje"].clip(lower=0, upper=100).round(1)

# Si una entidad no tiene consultorios esperados, se considera completa.
tabla_entidades.loc[tabla_entidades["esperadas"] == 0, "porcentaje"] = 100.0

tabla_entidades = tabla_entidades.sort_values(
    "porcentaje",
    ascending=False
)

In [ ]:
tabla_entidades

,entidad,consultorios,respondidas,esperadas,unidades,porcentaje
4,CIUDAD DE MEXICO,0.0,0.0,0.0,192,100.0
13,PUEBLA,1.0,42.0,44.0,16,95.5
5,COLIMA,65.0,2389.0,2860.0,60,83.5
18,TABASCO,62.0,2146.0,2728.0,132,78.7
19,TAMAULIPAS,139.0,4660.0,6116.0,150,76.2
16,SINALOA,66.0,2210.0,2904.0,66,76.1
1,BAJA CALIFORNIA SUR,39.0,1304.0,1716.0,51,76.0
14,QUINTANA ROO,136.0,4340.0,5984.0,133,72.5
6,GUERRERO,607.0,19362.0,26708.0,592,72.5
9,MICHOACAN DE OCAMPO,91.0,2846.0,4004.0,27,71.1
8,MEXICO,819.0,24109.0,36036.0,221,66.9
21,ZACATECAS,58.0,1655.0,2552.0,19,64.9
7,HIDALGO,67.0,1871.0,2948.0,24,63.5
0,BAJA CALIFORNIA,9.0,240.0,396.0,73,60.6
20,VERACRUZ DE IGNACIO DE LA LLAVE,131.0,3462.0,5764.0,74,60.1
15,SAN LUIS POTOSI,80.0,2066.0,3520.0,28,58.7
3,CHIAPAS,79.0,2002.0,3476.0,24,57.6
12,OAXACA,109.0,2730.0,4796.0,53,56.9
11,NAYARIT,84.0,2017.0,3696.0,56,54.6
17,SONORA,2.0,40.0,88.0,123,45.5
10,MORELOS,94.0,1755.0,4136.0,46,42.4
2,CAMPECHE,48.0,773.0,2112.0,31,36.6

In [ ]:
# Total de unidades por entidad (base completa)
total_por_entidad = (
    base
    .groupby("entidad")["clues_imb"]
    .nunique()
    .reset_index(name="total_unidades")
)

# Unidades que han respondido al menos una pregunta
# + unidades con consultorios_habilitados = 0 (se consideran atendidas)
respondieron_por_entidad = (
    pd.concat(
        [
            base_an[["entidad", "clues_imb"]],
            clues_sin_consultorios_estado[["entidad", "clues_imb"]],
        ],
        ignore_index=True,
    )
    .dropna(subset=["entidad", "clues_imb"])
    .drop_duplicates()
    .groupby("entidad")["clues_imb"]
    .nunique()
    .reset_index(name="unidades_respondieron")
)

tabla_avance = total_por_entidad.merge(
    respondieron_por_entidad,
    on="entidad",
    how="left"
)

tabla_avance["unidades_respondieron"] = (
    tabla_avance["unidades_respondieron"].fillna(0).astype(int)
)

tabla_avance["porcentaje"] = (
    tabla_avance["unidades_respondieron"]
    / tabla_avance["total_unidades"]
    * 100
).round(1)

tabla_avance = tabla_avance.sort_values("porcentaje", ascending=False)

In [ ]:
tabla_avance

,entidad,total_unidades,unidades_respondieron,porcentaje
8,MEXICO,221,221,100.0
7,HIDALGO,24,24,100.0
16,SINALOA,66,66,100.0
9,MICHOACAN DE OCAMPO,27,27,100.0
15,SAN LUIS POTOSI,28,27,96.4
3,CHIAPAS,24,23,95.8
21,ZACATECAS,19,18,94.7
11,NAYARIT,56,46,82.1
10,MORELOS,46,35,76.1
6,GUERRERO,592,418,70.6
5,COLIMA,60,42,70.0
14,QUINTANA ROO,133,92,69.2
20,VERACRUZ DE IGNACIO DE LA LLAVE,74,49,66.2
12,OAXACA,53,31,58.5
19,TAMAULIPAS,150,80,53.3
2,CAMPECHE,31,16,51.6
1,BAJA CALIFORNIA SUR,51,25,49.0
18,TABASCO,132,53,40.2
0,BAJA CALIFORNIA,73,7,9.6
13,PUEBLA,16,1,6.2
17,SONORA,123,2,1.6
4,CIUDAD DE MEXICO,192,0,0.0

## graficas

In [ ]:
import plotly.express as px

# Tabla base para la grafica
tabla = tabla_avance.sort_values("porcentaje", ascending=False).copy()

# Lista de CLUES faltantes por entidad para hover
faltantes_hover = (
    faltantes_por_estados
    .groupby("entidad")["clues_imb"]
    .apply(lambda s: "<br>".join(sorted(s.astype(str).unique())))
    .reset_index(name="clues_faltantes_hover")
)

tabla = tabla.merge(faltantes_hover, on="entidad", how="left")
tabla["clues_faltantes_hover"] = tabla["clues_faltantes_hover"].fillna("Sin CLUES faltantes")

# Semaforo de colores
tabla["color"] = tabla["porcentaje"].apply(
    lambda p:
        "#0D5D2A" if p == 100 else
        "#88A91E" if p >= 80 else
        "#F1D54A" if p >= 50 else
        "#D41111"
)

fig = px.bar(
    tabla,
    x="entidad",
    y="porcentaje",
    text="porcentaje",
    title="Avance por entidad sobre unidades",
    custom_data=["clues_faltantes_hover"]
)

fig.update_traces(
    marker_color=tabla["color"],
    texttemplate="%{text:.1f}%",
    textposition="outside",
    hovertemplate="<b>%{x}</b><br>CLUES faltantes:<br>%{customdata[0]}<extra></extra>"
)

fig.update_yaxes(showticklabels=False)

fig.update_layout(
    xaxis_title="",
    yaxis_title="",
    template="plotly_white",
    width=1200,
    height=700
)

In [ ]:
import plotly.graph_objects as go

# Ordenar de menor a mayor para efecto cascada
df_plot = tabla_entidades.sort_values("porcentaje", ascending=True)

# Semáforo de colores
colores = [
    "#0D5D2A" if p >= 95 else
    "#88A91E" if p >= 80 else
    "#F1D54A" if p >= 60 else
    "#D41111"
    for p in df_plot["porcentaje"]
]

fig_cascada = go.Figure()

fig_cascada.add_trace(
    go.Bar(
        x=df_plot["porcentaje"],
        y=df_plot["entidad"],
        orientation="h",
        marker=dict(color=colores),
        text=[f"{p:.1f}%" for p in df_plot["porcentaje"]],
        textposition="outside",
        textfont=dict(size=11),
        hovertemplate="<b>%{y}</b><br>Porcentaje: %{x:.1f}%<extra></extra>",
    )
)

fig_cascada.update_layout(
    title=dict(
        text="Gráfica de llenado de consultorios",
        x=0.5,
        font=dict(size=16)
    ),
    xaxis=dict(
        title="",
        range=[0, 115],
        ticksuffix="%",
        showgrid=True,
        gridcolor="lightgrey"
    ),
    yaxis=dict(
        title="",
        automargin=True
    ),
    plot_bgcolor="white",
    height=500,
    margin=dict(l=20, r=60, t=60, b=40)
)

In [ ]:
from pathlib import Path
import json
from datetime import datetime
from plotly.utils import PlotlyJSONEncoder

base_dir = Path.cwd()
salida_data = base_dir / "data.js"
html_origen = base_dir / "reporte_interactivo.html"
index_destino = base_dir / "index.html"

figures = [
    {"id": "fig_avance", "figure": fig.to_plotly_json()},
]

if "fig_cascada" in globals():
    figures.append({"id": "fig_cascada", "figure": fig_cascada.to_plotly_json()})
else:
    print("Aviso: fig_cascada no existe todavia; se exporta solo fig_avance.")

payload = {
    "title": "Tablero IMSS Bienestar",
    "updated_at": datetime.now().isoformat(timespec="seconds"),
    "tables": {
        "tabla_avance": {
            "columns": list(tabla_avance.columns),
            "rows": tabla_avance.to_dict(orient="records"),
            "excel": "tabla_avance.xlsx",
        },
        "tabla_entidades": {
            "columns": list(tabla_entidades.columns),
            "rows": tabla_entidades.to_dict(orient="records"),
            "excel": "tabla_entidades.xlsx",
        },
        "tabla_unidades": {
            "columns": list(tabla_unidades.columns),
            "rows": tabla_unidades.to_dict(orient="records"),
            "excel": "tabla_unidades.xlsx",
        },
        "faltantes_por_estados": {
            "columns": list(faltantes_por_estados.columns),
            "rows": faltantes_por_estados.to_dict(orient="records"),
            "excel": "faltantes_por_estados.xlsx",
        },
        "tabla_faltantes_por_estados": {
            "columns": list(tabla_faltantes_por_estados.columns),
            "rows": tabla_faltantes_por_estados.to_dict(orient="records"),
            "excel": "tabla_faltantes_por_estados.xlsx",
        },
    },
    "figures": figures,
}

contenido_js = "window.DASHBOARD_DATA = " + json.dumps(payload, ensure_ascii=False, cls=PlotlyJSONEncoder) + ";\n"
salida_data.write_text(contenido_js, encoding="utf-8")

# Si no existe el HTML origen, se crea desde index.html para que lo puedas editar
if not html_origen.exists() and index_destino.exists():
    html_origen.write_text(index_destino.read_text(encoding="utf-8"), encoding="utf-8")
    print(f"Se creo plantilla HTML: {html_origen}")

if html_origen.exists():
    index_destino.write_text(html_origen.read_text(encoding="utf-8"), encoding="utf-8")
    print(f"Index actualizado desde: {html_origen}")
# else:
#     print(f"No se encontro {html_origen.name}; index.html no se pudo actualizar.")

print(f"Datos exportados en: {salida_data}")
print("Ejecuta esta celda tras modificar graficas o HTML para refrescar el tablero.")

Index actualizado desde: c:\Users\jose.valdez\Downloads\nuevo-inf\informe--de-ang\reporte_interactivo.html
Datos exportados en: c:\Users\jose.valdez\Downloads\nuevo-inf\informe--de-ang\data.js
Ejecuta esta celda tras modificar graficas o HTML para refrescar el tablero.

In [ ]:
faltantes_por_estados

,entidad,clues_imb,nombre_de_la_unidad
0,BAJA CALIFORNIA,BCIMB000051,COLONIA LOMA LINDA
1,BAJA CALIFORNIA,BCIMB000063,COLONIA POPULAR 2
2,BAJA CALIFORNIA,BCIMB000075,COLONIA POPULAR 89
3,BAJA CALIFORNIA,BCIMB000104,COL. JALISCO
4,BAJA CALIFORNIA,BCIMB000116,COL. LOMITAS INDECO
...,...,...,...
884,VERACRUZ DE IGNACIO DE LA LLAVE,VZIMB007020,CENTRO DE SALUD TLAXCALITA
885,VERACRUZ DE IGNACIO DE LA LLAVE,VZIMB007032,CENTRO DE SALUD OVIEDO
886,VERACRUZ DE IGNACIO DE LA LLAVE,VZIMB007633,LA MAJAHUA
887,VERACRUZ DE IGNACIO DE LA LLAVE,VZIMB008543,C.S. JOPOY
888,ZACATECAS,ZSIMB001624,CENTRO DE SALUD COL. ESTRELLA DE ORO

In [ ]:
# Verificacion: no deben existir faltantes con consultorios_habilitados = 0
verificacion_faltantes_cero = (
    faltantes_por_estados
    .merge(
        consultorios_habilitados_por_unidad[["entidad", "clues_imb", "consultorios_habilitados"]],
        on=["entidad", "clues_imb"],
        how="left"
    )
    .query("consultorios_habilitados == 0")
)

print(f"Faltantes con consultorios_habilitados=0: {len(verificacion_faltantes_cero)}")
display(verificacion_faltantes_cero.head(20))

Faltantes con consultorios_habilitados=0: 0

Empty DataFrame
Columns: [entidad, clues_imb, nombre_de_la_unidad, consultorios_habilitados]
Index: []

: