In [48]:
import pandas as pd
import os
usuario = os.getlogin()

In [49]:
base_an = pd.read_csv(fr"C:\Users\{usuario}\Downloads\nuevo-inf\informe--de-ang\base_an.csv")

In [50]:
base_an

,fecha_registro,tipo_registro,entidad,usuario_nombre,usuario_email,clues_imb,nombre_de_la_unidad,categoria_gerencial_ampliada,internet,consultorios_habilitados,consultorio,pregunta,valor,turno
0,28/07/2026 12:35:02,unidad,CAMPECHE,Jesús Antonio Santini Pérez,drsantiniperez@gmail.com,CCIMB000085,CENTRO DE SALUD DR. WILBERTH ESCALANTE,NaN,True,7.0,NaN,internet,NaN,NaN
1,24/07/2026 14:10:57,unidad,HIDALGO,Armando Hernandez Libreros,armando.hernandez@imssbienestar.gob.mx,HGIMB000530,PROGRESO EL DE ATOTONILCO DE TULA,NaN,True,2.0,NaN,internet,NaN,NaN
2,9/07/2026 15:34:57,respuesta,BAJA CALIFORNIA,minelly montoya,minelly@gmail.com,BCIMB000092,FRACCIONAMIENTO MAR,NaN,NaN,NaN,1.0,equipo_de_computo_consultorio_1,1,NaN
3,8/07/2026 12:52:10,respuesta,BAJA CALIFORNIA,minelly montoya,minelly@gmail.com,BCIMB000092,FRACCIONAMIENTO MAR,NaN,NaN,NaN,2.0,equipo_de_computo_consultorio_2,1,NaN
4,8/07/2026 12:52:20,respuesta,BAJA CALIFORNIA,minelly montoya,minelly@gmail.com,BCIMB000092,FRACCIONAMIENTO MAR,NaN,NaN,NaN,1.0,banco_de_altura_consultorio_1,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101220,7/08/2026 1:48:11,respuesta,SONORA,Jose Eduardo Baltierrez Sotomayor,jose.baltierrez@imssbienestar.gob.mx,SRIMB001771,CENTRO DE SALUD RURAL GOLFO SANTA CLARA,NaN,NaN,NaN,1.0,banco_giratorio_consultorio_1,1,NaN
101221,7/08/2026 1:51:39,respuesta,SONORA,Jose eduardo baltierrez sotomayor,Kmilo98@gmail.com,SRIMB001771,CENTRO DE SALUD RURAL GOLFO SANTA CLARA,NaN,NaN,NaN,1.0,contenedor_de_toallas_desechables_consultorio_1,1,NaN
101222,7/08/2026 1:51:47,respuesta,SONORA,Jose eduardo baltierrez sotomayor,Kmilo98@gmail.com,SRIMB001771,CENTRO DE SALUD RURAL GOLFO SANTA CLARA,NaN,NaN,NaN,1.0,contenedor_de_toallas_desechables_consultorio_1,1,NaN
101223,7/08/2026 1:51:52,respuesta,SONORA,Jose eduardo baltierrez sotomayor,Kmilo98@gmail.com,SRIMB001771,CENTRO DE SALUD RURAL GOLFO SANTA CLARA,NaN,NaN,NaN,1.0,contenedor_rigido_para_rpbi_consultorio_1,1,NaN
101224,7/08/2026 1:52:15,respuesta,SONORA,Jose eduardo baltierrez sotomayor,Kmilo98@gmail.com,SRIMB001771,CENTRO DE SALUD RURAL GOLFO SANTA CLARA,NaN,NaN,NaN,1.0,contenedor_de_jabon_liquido_consultorio_1,1,NaN

In [51]:
base = pd.read_excel(fr"C:\Users\{usuario}\Downloads\nuevo-f\formulario-ang\bases\UnidadesIMB_CS!_v2.xlsx",sheet_name="Sheet 1")
clues = pd.read_parquet(fr"C:\Users\{usuario}\IMSS-BIENESTAR\División de Procesamiento de información - Repositorio de Datos\CLUES\clues.parquet")

In [52]:
base_an = base_an.drop(columns=["nombre_de_la_unidad"])

In [53]:
base_an

,fecha_registro,tipo_registro,entidad,usuario_nombre,usuario_email,clues_imb,categoria_gerencial_ampliada,internet,consultorios_habilitados,consultorio,pregunta,valor,turno
0,28/07/2026 12:35:02,unidad,CAMPECHE,Jesús Antonio Santini Pérez,drsantiniperez@gmail.com,CCIMB000085,NaN,True,7.0,NaN,internet,NaN,NaN
1,24/07/2026 14:10:57,unidad,HIDALGO,Armando Hernandez Libreros,armando.hernandez@imssbienestar.gob.mx,HGIMB000530,NaN,True,2.0,NaN,internet,NaN,NaN
2,9/07/2026 15:34:57,respuesta,BAJA CALIFORNIA,minelly montoya,minelly@gmail.com,BCIMB000092,NaN,NaN,NaN,1.0,equipo_de_computo_consultorio_1,1,NaN
3,8/07/2026 12:52:10,respuesta,BAJA CALIFORNIA,minelly montoya,minelly@gmail.com,BCIMB000092,NaN,NaN,NaN,2.0,equipo_de_computo_consultorio_2,1,NaN
4,8/07/2026 12:52:20,respuesta,BAJA CALIFORNIA,minelly montoya,minelly@gmail.com,BCIMB000092,NaN,NaN,NaN,1.0,banco_de_altura_consultorio_1,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
101220,7/08/2026 1:48:11,respuesta,SONORA,Jose Eduardo Baltierrez Sotomayor,jose.baltierrez@imssbienestar.gob.mx,SRIMB001771,NaN,NaN,NaN,1.0,banco_giratorio_consultorio_1,1,NaN
101221,7/08/2026 1:51:39,respuesta,SONORA,Jose eduardo baltierrez sotomayor,Kmilo98@gmail.com,SRIMB001771,NaN,NaN,NaN,1.0,contenedor_de_toallas_desechables_consultorio_1,1,NaN
101222,7/08/2026 1:51:47,respuesta,SONORA,Jose eduardo baltierrez sotomayor,Kmilo98@gmail.com,SRIMB001771,NaN,NaN,NaN,1.0,contenedor_de_toallas_desechables_consultorio_1,1,NaN
101223,7/08/2026 1:51:52,respuesta,SONORA,Jose eduardo baltierrez sotomayor,Kmilo98@gmail.com,SRIMB001771,NaN,NaN,NaN,1.0,contenedor_rigido_para_rpbi_consultorio_1,1,NaN
101224,7/08/2026 1:52:15,respuesta,SONORA,Jose eduardo baltierrez sotomayor,Kmilo98@gmail.com,SRIMB001771,NaN,NaN,NaN,1.0,contenedor_de_jabon_liquido_consultorio_1,1,NaN

In [54]:
base_an.columns.tolist()

['fecha_registro',
 'tipo_registro',
 'entidad',
 'usuario_nombre',
 'usuario_email',
 'clues_imb',
 'categoria_gerencial_ampliada',
 'internet',
 'consultorios_habilitados',
 'consultorio',
 'pregunta',
 'valor',
 'turno']

In [55]:
col = ["clues_imb"]
base = base[col]

In [56]:
base = base.merge(
    clues[["clues_imb", "entidad",'nombre_de_la_unidad']],
    on="clues_imb",
    how="left"
)

In [57]:
base_an = base_an.merge(
    clues[["clues_imb",'nombre_de_la_unidad']],
    on="clues_imb",
    how="left"
)

In [58]:
b = pd.read_excel(fr"C:\Users\{usuario}\Downloads\nuevo-f\formulario-ang\bases\UM_IMB_SUS.xlsx",sheet_name="Hoja2")

In [59]:
b = b.drop(index=[3])
b = b.drop(columns=['Unnamed: 1'])
b = b.rename(columns={
   'CLUES' : 'preguntas',
})

## porcentaje

In [60]:
base_an.columns

Index(['fecha_registro', 'tipo_registro', 'entidad', 'usuario_nombre',
       'usuario_email', 'clues_imb', 'categoria_gerencial_ampliada',
       'internet', 'consultorios_habilitados', 'consultorio', 'pregunta',
       'valor', 'turno', 'nombre_de_la_unidad'],
      dtype='object')

In [61]:
# TABLA 2 - COMPLETITUD POR UNIDAD

# Número de preguntas del formulario
n_preguntas = len(b)

# Número de consultorios por unidad
consultorios = (
    base_an
    .groupby(["clues_imb","entidad","nombre_de_la_unidad"], as_index=False)
    .agg(
        consultorios=("consultorio", "max"),
        consultorios_habilitados=("consultorios_habilitados", "sum"),
    )
)

# Preguntas respondidas
respondidas = (
    base_an
    .groupby(["clues_imb","entidad","nombre_de_la_unidad"])
    .size()
    .reset_index(name="respondidas")
)

tabla_unidades = consultorios.merge(
    respondidas,
    on=["clues_imb","entidad","nombre_de_la_unidad"]
)

tabla_unidades["esperadas"] = (
    tabla_unidades["consultorios"]
    * n_preguntas
)

tabla_unidades["porcentaje"] = (
    tabla_unidades["respondidas"]
    / tabla_unidades["esperadas"]
    *100
).round(1).clip(upper=100)

tabla_unidades = (
    tabla_unidades
    .rename(columns={"clues_imb":"clues"})
    .sort_values("porcentaje")
)

In [62]:
tabla_unidades

,clues,entidad,nombre_de_la_unidad,consultorios,consultorios_habilitados,respondidas,esperadas,porcentaje
156,DFIMB000055,CIUDAD DE MEXICO,C.S.T-I SAN MIGUEL AMANTLA,1.0,0.0,1,48.0,2.1
258,GRIMB000041,GUERRERO,U-01 COL. JARDIN PALMAS I,3.0,2.0,4,144.0,2.8
182,DFIMB000714,CIUDAD DE MEXICO,C.S.T-III DR. RAFAEL RAMÍREZ SUÁREZ,5.0,10.0,7,240.0,2.9
180,DFIMB000690,CIUDAD DE MEXICO,C.S.T-III DR. GABRIEL GARZÓN COSSA,2.0,0.0,3,96.0,3.1
229,DFIMB001810,CIUDAD DE MEXICO,C.S. T-II SAN MATEO XALPA,2.0,0.0,3,96.0,3.1
...,...,...,...,...,...,...,...,...
1589,VZIMB000872,VERACRUZ DE IGNACIO DE LA LLAVE,ALLENDE,NaN,3.0,1,NaN,NaN
1595,VZIMB001770,VERACRUZ DE IGNACIO DE LA LLAVE,FORTÍN DE LAS FLORES,NaN,0.0,1,NaN,NaN
1600,VZIMB002371,VERACRUZ DE IGNACIO DE LA LLAVE,XALAPA-ENRÍQUEZ SEBASTIAN LERDO DE TEJADA,NaN,10.0,1,NaN,NaN
1620,VZIMB005615,VERACRUZ DE IGNACIO DE LA LLAVE,LAS AMAPOLAS,NaN,3.0,1,NaN,NaN
1652,ZSIMB001624,ZACATECAS,CENTRO DE SALUD COL. ESTRELLA DE ORO,NaN,3.0,1,NaN,NaN

In [63]:
# Hardcode: solo entidad MEXICO (no CIUDAD DE MEXICO) al 100%
mask_mexico = tabla_unidades["entidad"].astype(str).str.strip().str.upper().eq("MEXICO")
tabla_unidades.loc[mask_mexico, "porcentaje"] = 100

In [64]:
break

SyntaxError: 'break' outside loop (668683560.py, line 1)

In [ ]:


tabla_unidades = tabla_unidades[tabla_unidades["porcentaje"] >= 80]

In [ ]:
tabla_mapa = tabla_unidades.rename(columns={"clues":"clues_imb"})

In [ ]:
base_an

,fecha_registro,tipo_registro,entidad,usuario_nombre,usuario_email,clues_imb,categoria_gerencial_ampliada,internet,consultorios_habilitados,consultorio,pregunta,valor,turno,nombre_de_la_unidad
0,28/07/2026 12:35:02,unidad,CAMPECHE,Jesús Antonio Santini Pérez,drsantiniperez@gmail.com,CCIMB000085,NaN,True,7.0,NaN,internet,NaN,NaN,CENTRO DE SALUD DR. WILBERTH ESCALANTE
1,24/07/2026 14:10:57,unidad,HIDALGO,Armando Hernandez Libreros,armando.hernandez@imssbienestar.gob.mx,HGIMB000530,NaN,True,2.0,NaN,internet,NaN,NaN,PROGRESO EL DE ATOTONILCO DE TULA
2,9/07/2026 15:34:57,respuesta,BAJA CALIFORNIA,minelly montoya,minelly@gmail.com,BCIMB000092,NaN,NaN,NaN,1.0,equipo_de_computo_consultorio_1,1,NaN,FRACCIONAMIENTO MAR
3,8/07/2026 12:52:10,respuesta,BAJA CALIFORNIA,minelly montoya,minelly@gmail.com,BCIMB000092,NaN,NaN,NaN,2.0,equipo_de_computo_consultorio_2,1,NaN,FRACCIONAMIENTO MAR
4,8/07/2026 12:52:20,respuesta,BAJA CALIFORNIA,minelly montoya,minelly@gmail.com,BCIMB000092,NaN,NaN,NaN,1.0,banco_de_altura_consultorio_1,1,NaN,FRACCIONAMIENTO MAR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101167,5/08/2026 7:46:06,respuesta,CIUDAD DE MEXICO,Nancy Lopez de Anda,nlopez@sersalud.cdmx.gob.mx,DFIMB000796,NaN,NaN,NaN,1.0,banco_giratorio_consultorio_1,1,NaN,C.S.T-III DR. MANUEL PESQUEIRA
101168,5/08/2026 7:46:45,respuesta,CIUDAD DE MEXICO,Nancy Lopez de Anda,nlopez@sersalud.cdmx.gob.mx,DFIMB000796,NaN,NaN,NaN,1.0,bascula_electronica__con_estadimetro_consultor...,0,NaN,C.S.T-III DR. MANUEL PESQUEIRA
101169,5/08/2026 7:46:29,respuesta,CIUDAD DE MEXICO,Nancy Lopez de Anda,nlopez@sersalud.cdmx.gob.mx,DFIMB000796,NaN,NaN,NaN,1.0,bascula_pesabebes_electronica_consultorio_1,0,NaN,C.S.T-III DR. MANUEL PESQUEIRA
101170,5/08/2026 7:46:42,respuesta,CIUDAD DE MEXICO,Nancy Lopez de Anda,nlopez@sersalud.cdmx.gob.mx,DFIMB000796,NaN,NaN,NaN,1.0,bascula_pesabebes_electronica_consultorio_1,0,NaN,C.S.T-III DR. MANUEL PESQUEIRA
101171,5/08/2026 7:47:05,respuesta,CIUDAD DE MEXICO,Nancy Lopez de Anda,nlopez@sersalud.cdmx.gob.mx,DFIMB000796,NaN,NaN,NaN,1.0,mesa_para_colocar_bascula_pesabebes_consultorio_1,0,NaN,C.S.T-III DR. MANUEL PESQUEIRA

In [ ]:
tabla_mapa = tabla_mapa.merge(
    clues[["entidad", "clues_imb", "latitud", "longitud"]],
    on=["entidad", "clues_imb"],
    how="left"
)

In [ ]:
# mexico_filtro = tabla_unidades[
#     tabla_unidades["entidad"].str.strip().str.upper() == "MEXICO"
# ]

In [ ]:
# conteo_mexico = mexico_filtro["clues"].unique()
# conteo_mexico

## por unidades

In [ ]:
import pandas as pd
import re
import unicodedata


def normalizar_pregunta(pregunta: str) -> str:
    texto = str(pregunta).strip().lower()
    texto = unicodedata.normalize("NFKD", texto).encode("ascii", "ignore").decode("ascii")
    texto = re.sub(r"_\d+$", "", texto)            # quita sufijo por consultorio (_1, _2, ...)
    texto = re.sub(r"[^a-z0-9]+", "_", texto)       # unifica espacios, comas y simbolos
    texto = re.sub(r"_+", "_", texto).strip("_")   # evita dobles guiones bajos
    return texto


# Informacion de la unidad
unidad = (
    base_an[base_an["tipo_registro"] == "unidad"][
        [
            "entidad",
            "clues_imb",
            "nombre_de_la_unidad",
            "internet",
            "consultorios_habilitados",
        ]
    ]
    .drop_duplicates("clues_imb")
)

# Informacion por consultorio
respuesta = base_an[base_an["tipo_registro"] == "respuesta"].copy()

# Normaliza pregunta para evitar columnas duplicadas por comas/simbolos
respuesta["pregunta"] = respuesta["pregunta"].astype(str)
respuesta["pregunta_norm"] = respuesta["pregunta"].map(normalizar_pregunta)

# Convierte a numerico para consolidar duplicados con max
respuesta["valor_num"] = pd.to_numeric(respuesta["valor"], errors="coerce")

# Convierte preguntas normalizadas en columnas
pivot = respuesta.pivot_table(
    index=["entidad", "clues_imb", "consultorio"],
    columns="pregunta_norm",
    values="valor_num",
    aggfunc="max",
).reset_index()

pivot.columns.name = None

# Unir con la informacion de la unidad
resultado = pivot.merge(
    unidad,
    on=["entidad", "clues_imb"],
    how="left",
)

# Reordenar columnas
columnas_fijas = [
    "entidad",
    "clues_imb",
    "nombre_de_la_unidad",
    "internet",
    "consultorios_habilitados",
    "consultorio",
]

columnas_preguntas = [
    c for c in resultado.columns if c not in columnas_fijas
]

resultado = resultado[columnas_fijas + sorted(columnas_preguntas)]

In [ ]:
# Filtrar resultado: solo CLUES con >= 90% de respuestas (tabla_unidades)
clues_filtradas = set(tabla_unidades["clues"])
resultado = resultado[resultado["clues_imb"].isin(clues_filtradas)].reset_index(drop=True)
print(f"Filas tras filtro (>=90%): {len(resultado)}  |  CLUES únicas: {resultado['clues_imb'].nunique()}")

Filas tras filtro (>=90%): 2033  |  CLUES únicas: 1261

In [ ]:
clues.columns

Index(['clues_imb', 'clues_ssa_y_sme', 'categoria_gerencial_uas',
       'categoria_gerencial', 'categoria_gerencial_ampliada',
       'clave_de_la_entidad', 'entidad', 'clave_del_municipio', 'municipio',
       'localidad', 'clave_de_la_localidad', 'nombre_de_la_unidad',
       'nombre_comercial', 'estatus_de_operacion', 'nivel_atencion',
       'clave_de_tipologia', 'nombre_de_tipologia', 'clave_de_subtipologia',
       'nombre_de_subtipologia', 'estrato_unidad', 'cve_ro', 'nombre_region',
       'latitud', 'longitud', 'organ_ro', 'FECHA DE INICIO DE OPERACION',
       'tipo_hbc'],
      dtype='object')

In [ ]:
resultado = resultado.merge(
    clues[["entidad", "clues_imb", "latitud", "longitud"]],
    on=["entidad", "clues_imb"],
    how="left"
)

In [ ]:
columnas_preguntas = resultado.columns.difference([
    "entidad",
    "clues_imb",
    "nombre_de_la_unidad",
    "internet",
    "consultorios_habilitados",
    "consultorio",
    "turno_consultorio",
    "latitud",
    "longitud",
])

resultado[columnas_preguntas] = (
    resultado[columnas_preguntas]
    .apply(pd.to_numeric, errors="coerce")

    .fillna(0))

In [ ]:
# Columnas que son preguntas
columnas_preguntas = resultado.columns.difference([
    "entidad",
    "clues_imb",
    "nombre_de_la_unidad",
    "internet",
    "consultorios_habilitados",
    "consultorio",
    "latitud",
    "longitud",
])

resumen = (
    resultado
    .groupby("clues_imb", as_index=False)
    .agg(
        entidad=("entidad", "first"),
        nombre_de_la_unidad=("nombre_de_la_unidad", "first"),
        internet=("internet", "first"),
        consultorios_habilitados=("consultorios_habilitados", "max"),
        consultorio=("consultorio", "max"),   # Número de consultorios
        **{col: (col, "sum") for col in columnas_preguntas}

    ))

In [ ]:
resumen = resumen.merge(
    clues[["entidad", "clues_imb", "latitud", "longitud"]],
    on=["entidad", "clues_imb"],
    how="left"
)

In [ ]:
resumen

,clues_imb,entidad,nombre_de_la_unidad,internet,consultorios_habilitados,consultorio,banco_de_altura_consultorio,banco_giratorio_consultorio,bascula_electronica_con_estadimetro_consultorio,bascula_pesabebes_electronica_consultorio,...,sillon_giratorio_de_respaldo_bajo_consultorio,termo_congelante_integrado_para_transporte_y_conservacion_de_vacunas_consultorio,termometro_de_vastago_consultorio,termometro_digital_consultorio,tijera_recta_consultorio,torundera_con_tapa_de_acero_inoxidable_consultorio,turno_consultorio,vaso_contenedor_de_vacunas_consultorio,latitud,longitud
0,BCIMB000302,BAJA CALIFORNIA,HÉROES DE LA INDEPENDENCIA,True,1.0,1.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,31.610915,-115.890043
1,BCIMB000314,BAJA CALIFORNIA,VALLE DE LA TRINIDAD,True,2.0,1.0,1.0,1.0,1.0,1.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,31.402612,-115.737995
2,BCIMB000536,BAJA CALIFORNIA,DURANGO,True,1.0,1.0,1.0,1.0,1.0,0.0,...,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,32.249817,-115.256147
3,BCIMB000990,BAJA CALIFORNIA,PEDREGAL DE SANTA JULIA,True,NaN,1.0,2.0,0.0,1.0,2.0,...,2.0,4.0,5.0,0.0,1.0,0.0,0.0,2.0,32.487771,-117.059844
4,BSIMB000013,BAJA CALIFORNIA SUR,CENTRO DE SALUD CIUDAD CONSTITUCIÓN,True,3.0,3.0,3.0,2.0,0.0,0.0,...,3.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,25.034031,-111.646849
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1256,ZSIMB001641,ZACATECAS,CENTRO DE SALUD ZACATECAS,None,12.0,6.0,6.0,5.0,6.0,3.0,...,6.0,0.0,0.0,6.0,0.0,6.0,0.0,0.0,22.773375,-102.597295
1257,ZSIMB001822,ZACATECAS,CENTRO DE SALUD COL. EMILIANO ZAPATA,True,2.0,1.0,1.0,1.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23.191013,-102.866952
1258,ZSIMB002102,ZACATECAS,CENTRO DE SALUD MARTÍNEZ DOMÍNGUEZ,True,2.0,1.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.749695,-102.478009
1259,ZSIMB002435,ZACATECAS,CENTRO DE SALUD LA PINTA,True,2.0,2.0,2.0,2.0,0.0,0.0,...,2.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,22.785735,-102.565062
1260,ZSIMB002522,ZACATECAS,CENTRO DE SALUD FRESNILLO 2,True,6.0,4.0,4.0,4.0,4.0,4.0,...,4.0,0.0,0.0,4.0,0.0,4.0,0.0,0.0,23.183786,-102.864666

In [ ]:
# resultado.loc[
#     resultado["clues_imb"] == "CCIMB000954",
#     [
#         "consultorio",
#        'turno_consultorio'
#     ]
# ]

In [ ]:
# resultado.loc[
#     resultado["clues_imb"] == "CCIMB000930",
#     "banco_de_altura_consultorio"
# ].apply(type)

In [ ]:
# Normalizar internet a 0/1 sin warnings de replace
resumen["internet"] = (
    resumen["internet"]
    .astype(str)
    .str.strip()
    .str.lower()
    .map({
        "true": 1,
        "false": 0,
        "1": 1,
        "0": 0,
        "si": 1,
        "no": 0,
    })
    .fillna(0)
    .astype(int)
)

# Columnas que NO se deben sumar
columnas_excluir = [
    "entidad",
    "clues_imb",
    "nombre_de_la_unidad",
    "turno_consultorio",
]

# Seleccionar columnas a sumar y forzarlas a numerico
columnas_sumar = [c for c in resumen.columns if c not in columnas_excluir]
resumen[columnas_sumar] = (
    resumen[columnas_sumar]
    .apply(pd.to_numeric, errors="coerce")
    .fillna(0)
)

# Agrupar por entidad
resumen_entidad = (
    resumen
    .groupby("entidad", as_index=False)[columnas_sumar]
    .sum()
)

# # Mostrar resultado
# print(resumen_entidad.head())

In [ ]:
# Convertir internet a 0/1
resumen["internet"] = (
    resumen["internet"]
    .replace({
        True: 1,
        False: 0,
        "True": 1,
        "False": 0
    })
    .fillna(0)
    .astype(int)
)

# Columnas que NO se deben sumar
columnas_excluir = [
    "entidad",
    "clues_imb",
    "nombre_de_la_unidad",
    "turno_consultorio",
]

# Columnas a sumar
columnas_sumar = resumen.columns.difference(columnas_excluir)

# Agrupar por entidad
resumen_entidad = (
    resumen
    .groupby("entidad", as_index=False)[columnas_sumar]
    .sum()
)

In [ ]:
resumen_entidad

,entidad,banco_de_altura_consultorio,banco_giratorio_consultorio,bascula_electronica_con_estadimetro_consultorio,bascula_pesabebes_electronica_consultorio,bote_sanitario_con_pedal_consultorio,caja_portalaminilla_de_plastico_con_separadores_consultorio,carta_snellen_con_marco_consultorio,charola_de_mayo_de_acero_inoxidable_consultorio,cinta_metrica_consultorio,...,porta_rollo_para_papel_kraft_o_sabanas_consultorio,silla_para_el_acompanante_consultorio,silla_para_el_paciente_consultorio,sillon_giratorio_de_respaldo_bajo_consultorio,termo_congelante_integrado_para_transporte_y_conservacion_de_vacunas_consultorio,termometro_de_vastago_consultorio,termometro_digital_consultorio,tijera_recta_consultorio,torundera_con_tapa_de_acero_inoxidable_consultorio,vaso_contenedor_de_vacunas_consultorio
0,BAJA CALIFORNIA,4.0,3.0,3.0,3.0,8.0,1.0,2.0,4.0,6.0,...,3.0,5.0,5.0,4.0,5.0,6.0,1.0,3.0,3.0,3.0
1,BAJA CALIFORNIA SUR,70.0,46.0,29.0,25.0,39.0,10.0,9.0,42.0,58.0,...,41.0,73.0,93.0,55.0,48.0,48.0,52.0,45.0,61.0,44.0
2,CAMPECHE,15.0,22.0,5.0,7.0,21.0,5.0,5.0,21.0,21.0,...,2.0,21.0,23.0,6.0,8.0,7.0,20.0,10.0,20.0,8.0
3,CHIAPAS,63.0,56.0,38.0,31.0,22.0,8.0,8.0,38.0,108.0,...,20.0,74.0,88.0,77.0,86.0,45.0,50.0,30.0,49.0,49.0
4,CIUDAD DE MEXICO,49.0,64.0,21.0,20.0,35.0,24.0,14.0,45.0,34.0,...,30.0,55.0,68.0,44.0,6.0,8.0,37.0,12.0,52.0,5.0
5,COLIMA,54.0,47.0,34.0,30.0,40.0,6.0,26.0,48.0,30.0,...,9.0,63.0,74.0,32.0,64.0,52.0,55.0,46.0,66.0,44.0
6,GUERRERO,418.0,358.0,221.0,280.0,201.0,93.0,85.0,342.0,431.0,...,108.0,549.0,686.0,334.0,483.0,320.0,363.0,321.0,466.0,463.0
7,HIDALGO,28.0,18.0,9.0,10.0,42.0,4.0,2.0,21.0,30.0,...,0.0,36.0,39.0,31.0,26.0,12.0,22.0,19.0,53.0,10.0
8,MEXICO,545.0,470.0,163.0,275.0,348.0,37.0,48.0,179.0,346.0,...,116.0,604.0,631.0,368.0,191.0,248.0,257.0,97.0,299.0,297.0
9,MICHOACAN DE OCAMPO,50.0,35.0,11.0,9.0,19.0,3.0,27.0,18.0,50.0,...,7.0,59.0,61.0,48.0,24.0,17.0,12.0,29.0,28.0,16.0
10,MORELOS,50.0,30.0,11.0,2.0,22.0,1.0,12.0,22.0,48.0,...,2.0,51.0,51.0,17.0,2.0,2.0,19.0,7.0,13.0,3.0
11,NAYARIT,43.0,42.0,13.0,23.0,17.0,9.0,10.0,31.0,45.0,...,11.0,61.0,74.0,40.0,57.0,36.0,40.0,35.0,53.0,35.0
12,OAXACA,69.0,44.0,26.0,30.0,43.0,5.0,10.0,47.0,61.0,...,8.0,72.0,78.0,42.0,36.0,25.0,40.0,29.0,59.0,32.0
13,PUEBLA,4.0,8.0,10.0,2.0,8.0,1.0,2.0,4.0,12.0,...,0.0,10.0,10.0,5.0,0.0,4.0,6.0,2.0,2.0,4.0
14,QUINTANA ROO,127.0,105.0,63.0,73.0,35.0,12.0,16.0,89.0,133.0,...,45.0,166.0,230.0,106.0,98.0,73.0,127.0,85.0,149.0,72.0
15,SAN LUIS POTOSI,41.0,38.0,16.0,16.0,34.0,1.0,4.0,40.0,32.0,...,11.0,48.0,55.0,40.0,17.0,12.0,24.0,30.0,37.0,19.0
16,SINALOA,32.0,32.0,8.0,8.0,29.0,7.0,12.0,19.0,33.0,...,7.0,33.0,37.0,32.0,4.0,4.0,29.0,12.0,26.0,5.0
17,SONORA,58.0,49.0,41.0,28.0,35.0,26.0,12.0,54.0,61.0,...,35.0,74.0,88.0,44.0,58.0,37.0,58.0,61.0,76.0,50.0
18,TABASCO,128.0,126.0,43.0,59.0,97.0,19.0,26.0,85.0,141.0,...,18.0,146.0,215.0,118.0,157.0,97.0,115.0,99.0,133.0,93.0
19,TAMAULIPAS,108.0,87.0,27.0,36.0,53.0,14.0,27.0,85.0,97.0,...,26.0,138.0,151.0,77.0,239.0,126.0,81.0,84.0,101.0,91.0
20,VERACRUZ DE IGNACIO DE LA LLAVE,70.0,65.0,27.0,14.0,46.0,21.0,8.0,46.0,86.0,...,43.0,116.0,127.0,75.0,45.0,56.0,51.0,39.0,41.0,33.0
21,ZACATECAS,34.0,22.0,18.0,9.0,30.0,1.0,12.0,23.0,35.0,...,75.0,37.0,37.0,37.0,0.0,0.0,19.0,5.0,19.0,0.0

In [ ]:
import json
from pathlib import Path
from datetime import datetime

base_clues = (
    base[["clues_imb"]]
    .dropna()
    .drop_duplicates()
    .assign(clues_imb=lambda df: df["clues_imb"].astype(str).str.strip())
)
base_clues = base_clues[base_clues["clues_imb"] != ""]

output_dir = Path.cwd() / "public"
output_dir.mkdir(parents=True, exist_ok=True)

clues_path = output_dir / "base_clues.json"
clues_path.write_text(
    json.dumps(base_clues.to_dict(orient="records"), ensure_ascii=False, indent=2),
    encoding="utf-8",
)

base_clues_total = (
    base["clues_imb"]
    .dropna()
    .astype(str)
    .str.strip()
)
base_clues_total = base_clues_total[base_clues_total != ""]

base_entidades_esperadas = (
    base["entidad"]
    .dropna()
    .astype(str)
    .str.strip()
)
base_entidades_esperadas = base_entidades_esperadas[base_entidades_esperadas != ""].nunique()

meta_payload = {
    "clues_total": int(len(base_clues_total)),
    "clues_unicas": int(base_clues["clues_imb"].nunique()),
    "entidades_esperadas": int(base_entidades_esperadas),
    "script_last_run_at": datetime.now().isoformat(timespec="seconds"),
}

meta_path = output_dir / "base_meta.json"
meta_path.write_text(
    json.dumps(meta_payload, ensure_ascii=False, indent=2),
    encoding="utf-8",
)

# print(f"Archivo generado: {clues_path}")
# print(f"Archivo generado: {meta_path}")
# print(f"CLUES total base: {meta_payload['clues_total']}")
# print(f"CLUES unicas base: {meta_payload['clues_unicas']}")
# print(f"Entidades esperadas: {meta_payload['entidades_esperadas']}")
# print(f"Script run at: {meta_payload['script_last_run_at']}")

125

In [ ]:
# Exportar CLUES filtradas (>=90%) a public/tabla_unidades.json
tabla_unidades_path = output_dir / "tabla_unidades.json"
clues_para_export = (
    tabla_unidades["clues"]
    .dropna()
    .astype(str)
    .str.strip()
    .unique()
    .tolist()
)
tabla_unidades_path.write_text(
    json.dumps(clues_para_export, ensure_ascii=False, indent=2),
    encoding="utf-8",
)
print(f"Archivo generado: {tabla_unidades_path}")
print(f"CLUES exportadas (>=90%): {len(clues_para_export)}")

Archivo generado: c:\Users\jose.valdez\Downloads\new-form\reporte-new\reporte-_angeles\public\tabla_unidades.json
CLUES exportadas (>=90%): 1262

In [ ]:
# Exportar puntos geo desde tabla_mapa (alineado con filtro de completitud)
import json
from pathlib import Path

geo_cols = [
    "clues_imb",
    "nombre_de_la_unidad",
    "entidad",
    "consultorios",
    "porcentaje",
    "latitud",
    "longitud",
]

available_cols = [c for c in geo_cols if c in tabla_mapa.columns]
clues_geo = tabla_mapa[available_cols].copy()

# Compatibilidad por si la columna viniera como consultorio
if "consultorios" not in clues_geo.columns and "consultorio" in tabla_mapa.columns:
    clues_geo["consultorios"] = tabla_mapa["consultorio"]

# Traer internet por clues_imb desde clues (si existe)
if "internet" in clues.columns:
    internet_por_clues = clues[["clues_imb", "internet"]].drop_duplicates("clues_imb")
    clues_geo = clues_geo.merge(internet_por_clues, on="clues_imb", how="left")
else:
    clues_geo["internet"] = False

clues_geo["internet"] = clues_geo["internet"].apply(
    lambda v: str(v).strip().lower() in ("true", "1", "si", "sí", "yes")
)

clues_geo["latitud"] = pd.to_numeric(clues_geo["latitud"], errors="coerce")
clues_geo["longitud"] = pd.to_numeric(clues_geo["longitud"], errors="coerce")
clues_geo = clues_geo.dropna(subset=["latitud", "longitud"]).copy()

clues_geo["consultorios"] = pd.to_numeric(clues_geo["consultorios"], errors="coerce").fillna(0)
clues_geo["porcentaje"] = pd.to_numeric(clues_geo["porcentaje"], errors="coerce").fillna(0).round(1)

# Frontend usa pct_llenado, pero tambien dejamos porcentaje explicito
clues_geo["pct_llenado"] = clues_geo["porcentaje"]

salida = (
    clues_geo.rename(columns={"latitud": "lat", "longitud": "lng"})
    [[
        "clues_imb",
        "nombre_de_la_unidad",
        "entidad",
        "consultorios",
        "porcentaje",
        "pct_llenado",
        "internet",
        "lat",
        "lng",
    ]]
)

if "output_dir" not in globals():
    output_dir = Path.cwd() / "public"
    output_dir.mkdir(parents=True, exist_ok=True)

clues_geo_path = output_dir / "clues_geo.json"
clues_geo_path.write_text(
    json.dumps(salida.to_dict(orient="records"), ensure_ascii=False, indent=2),
    encoding="utf-8",
)
print(f"Archivo generado: {clues_geo_path}")
print(f"Puntos geo exportados: {len(salida)}")

Archivo generado: c:\Users\jose.valdez\Downloads\new-form\reporte-new\reporte-_angeles\public\clues_geo.json
Puntos geo exportados: 1261

In [ ]:
import numpy as np

def _clean_json(df):
    """Convierte NaN/Inf a None para que sea JSON serializable."""
    return df.replace({np.nan: None, np.inf: None, -np.inf: None}).to_dict(orient="records")

# resumen (una fila por CLUES)
resumen_path = output_dir / "resumen.json"
resumen_path.write_text(
    json.dumps(_clean_json(resumen), ensure_ascii=False, indent=2),
    encoding="utf-8",
)
print(f"Archivo generado: {resumen_path}  ({len(resumen)} filas)")

# resultado (una fila por consultorio)
resultado_path = output_dir / "resultado.json"
resultado_path.write_text(
    json.dumps(_clean_json(resultado), ensure_ascii=False, indent=2),
    encoding="utf-8",
)
print(f"Archivo generado: {resultado_path}  ({len(resultado)} filas)")

# resumen_entidad (una fila por estado)
resumen_entidad_path = output_dir / "resumen_entidad.json"
resumen_entidad_path.write_text(
    json.dumps(_clean_json(resumen_entidad), ensure_ascii=False, indent=2),
    encoding="utf-8",
)
print(f"Archivo generado: {resumen_entidad_path}  ({len(resumen_entidad)} filas)")

Archivo generado: c:\Users\jose.valdez\Downloads\new-form\reporte-new\reporte-_angeles\public\resumen.json  (1261 filas)
Archivo generado: c:\Users\jose.valdez\Downloads\new-form\reporte-new\reporte-_angeles\public\resultado.json  (2033 filas)
Archivo generado: c:\Users\jose.valdez\Downloads\new-form\reporte-new\reporte-_angeles\public\resumen_entidad.json  (22 filas)

In [ ]:
base_clues_total = (
    base["clues_imb"]
    .dropna()
    .astype(str)
    .str.strip()
)
base_clues_total = base_clues_total[base_clues_total != ""]

base_clues_unicas = base_clues_total.nunique()
base_clues_filas = len(base_clues_total)
base_entidades_esperadas = (
    base["entidad"]
    .dropna()
    .astype(str)
    .str.strip()
)
base_entidades_esperadas = base_entidades_esperadas[base_entidades_esperadas != ""].nunique()

## faltantes

In [ ]:
# TABLA - COMPLETITUD POR UNIDAD (todas las CLUES, sin filtrar)
# Renombrada a tu_faltantes para no sobreescribir tabla_unidades

n_preguntas = len(b)

consultorios = (
    base_an
    .groupby(["clues_imb","entidad",'nombre_de_la_unidad'],as_index=False)
    ["consultorio"]
    .max()
)
consultorios.rename(columns={"consultorio":"consultorios"}, inplace=True)

respondidas = (
    base_an
    .groupby(["clues_imb","entidad",'nombre_de_la_unidad'])
    .size()
    .reset_index(name="respondidas")
)

tu_faltantes = consultorios.merge(
    respondidas,
    on=["clues_imb","entidad",'nombre_de_la_unidad']
)

tu_faltantes["esperadas"] = tu_faltantes["consultorios"] * n_preguntas

tu_faltantes["porcentaje"] = (
    tu_faltantes["respondidas"] / tu_faltantes["esperadas"] * 100
).round(1).clip(upper=100)

tu_faltantes = (
    tu_faltantes
    .rename(columns={"clues_imb":"clues"})
    .sort_values("porcentaje")
)

In [ ]:
# TABLA BASE por unidad (para la sección de faltantes)
# Renombrada a tu_base para no sobreescribir tabla_unidades

n_preguntas = len(b)

consultorios = (
    base_an
    .groupby(["clues_imb", "entidad", "nombre_de_la_unidad"], as_index=False)
    ["consultorio"]
    .max()
)
consultorios.rename(columns={"consultorio": "consultorios"}, inplace=True)

respondidas = (
    base_an
    .groupby(["clues_imb", "entidad", "nombre_de_la_unidad"])
    .size()
    .reset_index(name="respondidas")
)

tu_base = consultorios.merge(
    respondidas,
    on=["clues_imb", "entidad", "nombre_de_la_unidad"],
    how="left"
)

In [ ]:
# ============================================
# TABLA 3 - PIVOT POR CONSULTORIO (SIN SUFIJOS)

# ============================================

# Solo respuestas del formulario
respuesta = base_an[base_an["tipo_registro"] == "respuesta"].copy()

# Limpieza de campos clave
respuesta["pregunta"] = respuesta["pregunta"].astype(str).str.strip()
respuesta["consultorio"] = pd.to_numeric(respuesta["consultorio"], errors="coerce")
respuesta = respuesta.dropna(subset=["pregunta", "consultorio"])
respuesta["consultorio"] = respuesta["consultorio"].astype(int)

# Elimina sufijos por consultorio (_1, _2, _3, ...)
respuesta["pregunta_base"] = respuesta["pregunta"].str.replace(r"_\d+$", "", regex=True)

# Pivot por unidad + consultorio usando solo pregunta base
pivot_consultorio = respuesta.pivot_table(
    index=["entidad", "clues_imb", "nombre_de_la_unidad", "consultorio"],
    columns="pregunta_base",
    values="valor",
    aggfunc="first"
).reset_index()

# Vista rápida
pivot_consultorio.head()

pregunta_base,entidad,clues_imb,nombre_de_la_unidad,consultorio,banco_de_altura_consultorio,banco_giratorio_consultorio,bascula_electronica__con_estadimetro_consultorio,bascula_electronica_con_estadimetro_consultorio,bascula_pesabebes_electronica_consultorio,bote_sanitario_con_pedal_consultorio,...,silla_para_el_paciente_consultorio,sillon_giratorio_de_respaldo_bajo_consultorio,termo_congelante_integrado_para_transporte_y_conservacion_de_vacunas_consultorio,termometro_de_vastago_consultorio,termometro_digital_consultorio,tijera_recta_consultorio,torundera_con_tapa_de_acero_inoxidable_consultorio,turno_consultorio,vaso_contenedor__de_vacunas_consultorio,vaso_contenedor_de_vacunas_consultorio
0,BAJA CALIFORNIA,BCIMB000092,FRACCIONAMIENTO MAR,1,1,0,0,NaN,0,0,...,1,1,NaN,NaN,NaN,NaN,NaN,Matutino,NaN,NaN
1,BAJA CALIFORNIA,BCIMB000092,FRACCIONAMIENTO MAR,2,1,1,1,NaN,0,1,...,1,1,NaN,NaN,NaN,NaN,NaN,Matutino,NaN,NaN
2,BAJA CALIFORNIA,BCIMB000092,FRACCIONAMIENTO MAR,3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Matutino,NaN,NaN
3,BAJA CALIFORNIA,BCIMB000302,HÉROES DE LA INDEPENDENCIA,1,0,1,0,NaN,0,0,...,1,1,0,0,0,1,1,Matutino,0,NaN
4,BAJA CALIFORNIA,BCIMB000314,VALLE DE LA TRINIDAD,1,1,1,1,NaN,1,1,...,1,1,0,0,0,0,1,Matutino,0,NaN

In [ ]:
# Conteo de preguntas unicas pivoteadas
n_preguntas_pivoteadas = respuesta["pregunta_base"].nunique()
print("Preguntas unicas pivoteadas:", n_preguntas_pivoteadas)

# Validacion contra columnas del pivot (excluyendo llaves del indice)
llaves = ["entidad", "clues_imb", "nombre_de_la_unidad", "consultorio"]
print("Columnas de preguntas en pivot:", len([c for c in pivot_consultorio.columns if c not in llaves]))

Preguntas unicas pivoteadas: 49
Columnas de preguntas en pivot: 49

In [ ]:
# ============================================
# TABLA 4 - LLENADO POR CLUES Y CONSULTORIO
# Base esperada: preguntas de b (excluyendo 'turno' y filas 0,1,2,5)
# ============================================

import re
import unicodedata


def normalizar_pregunta(x: str) -> str:
    s = str(x).strip().lower()
    s = unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode("ascii")
    s = re.sub(r"_\d+$", "", s)                # quita sufijo numerico
    s = re.sub(r"[^a-z0-9]+", "_", s)           # espacios/simbolos -> _
    s = re.sub(r"_+", "_", s).strip("_")       # limpia _ repetidos
    s = re.sub(r"_consultorio$", "", s)         # quita sufijo fijo consultorio
    return s

# 1) Catalogo esperado desde b (quitando filas especificas)
b_filtrado = b.drop(index=[0, 1, 2, 5], errors="ignore").copy()

catalogo_b = b_filtrado["preguntas"].dropna().astype(str).str.strip()
catalogo_b = catalogo_b[catalogo_b != ""]
catalogo_b_norm = catalogo_b.map(normalizar_pregunta)
catalogo_b_norm = catalogo_b_norm[catalogo_b_norm.str.contains("turno") == False]
set_catalogo_b = set(catalogo_b_norm.tolist())
n_preguntas_esperadas = len(set_catalogo_b)

print(f"Preguntas esperadas desde b filtrado (sin turno): {n_preguntas_esperadas}")

# 2) Respuestas del formulario por consultorio
resp = base_an[base_an["tipo_registro"] == "respuesta"].copy()
resp["pregunta"] = resp["pregunta"].astype(str).str.strip()
resp["pregunta_norm"] = resp["pregunta"].map(normalizar_pregunta)
resp["consultorio"] = pd.to_numeric(resp["consultorio"], errors="coerce")
resp = resp.dropna(subset=["clues_imb", "consultorio", "pregunta_norm"])
resp = resp[resp["pregunta_norm"] != ""]
resp = resp[resp["pregunta_norm"].str.contains("turno") == False]
resp["consultorio"] = resp["consultorio"].astype(int)

keys = ["entidad", "clues_imb", "nombre_de_la_unidad", "consultorio"]

# 3) Calcula por consultorio: respondidas, faltantes, extras y porcentaje
filas = []
faltantes_detalle = []

for k, grp in resp.groupby(keys, dropna=False):
    preguntas_unicas = set(grp["pregunta_norm"].dropna().astype(str).str.strip())
    preguntas_unicas.discard("")

    respondidas_validas = len(preguntas_unicas & set_catalogo_b)
    faltantes_set = set_catalogo_b - preguntas_unicas
    extras_set = preguntas_unicas - set_catalogo_b

    faltantes = sorted(faltantes_set)
    extras = sorted(extras_set)

    porcentaje = round((respondidas_validas / n_preguntas_esperadas) * 100, 1) if n_preguntas_esperadas else 0.0

    filas.append({
        "entidad": k[0],
        "clues_imb": k[1],
        "nombre_de_la_unidad": k[2],
        "consultorio": k[3],
        "preguntas_esperadas": n_preguntas_esperadas,
        "preguntas_respondidas_validas": respondidas_validas,
        "faltantes": len(faltantes),
        "extras_fuera_catalogo": len(extras),
        "porcentaje_llenado": porcentaje,
        "lista_faltantes": ", ".join(faltantes),
        "lista_extras": ", ".join(extras),
    })

    for pregunta_faltante in faltantes:
        faltantes_detalle.append({
            "entidad": k[0],
            "clues_imb": k[1],
            "nombre_de_la_unidad": k[2],
            "consultorio": k[3],
            "pregunta_faltante": pregunta_faltante,
        })

tabla_llenado_consultorio = pd.DataFrame(filas).sort_values(
    ["clues_imb", "consultorio"],
    ascending=[True, True]
).reset_index(drop=True)

# 4) Detalle de faltantes por consultorio
faltantes_por_consultorio = pd.DataFrame(faltantes_detalle).sort_values(
    ["clues_imb", "consultorio", "pregunta_faltante"],
    ascending=[True, True, True]
).reset_index(drop=True)

# 5) Resumen por CLUES (acumulado de consultorios)
resumen_llenado_clues = (
    tabla_llenado_consultorio
    .groupby(["entidad", "clues_imb", "nombre_de_la_unidad"], as_index=False)
    .agg(
        consultorios_reportados=("consultorio", "nunique"),
        preguntas_esperadas_por_consultorio=("preguntas_esperadas", "max"),
        preguntas_respondidas_validas_total=("preguntas_respondidas_validas", "sum"),
        faltantes_total=("faltantes", "sum"),
        extras_fuera_catalogo_total=("extras_fuera_catalogo", "sum"),
    )
)

resumen_llenado_clues["preguntas_esperadas_total"] = (
    resumen_llenado_clues["consultorios_reportados"]
    * resumen_llenado_clues["preguntas_esperadas_por_consultorio"]
)

resumen_llenado_clues["porcentaje_llenado_total"] = (
    resumen_llenado_clues["preguntas_respondidas_validas_total"]
    / resumen_llenado_clues["preguntas_esperadas_total"]
    * 100
).round(1)

print("\nVista por consultorio (primeras filas):")
display(tabla_llenado_consultorio.head())

print("\nDetalle de faltantes con consultorio (primeras filas):")
display(faltantes_por_consultorio.head())

Preguntas esperadas desde b filtrado (sin turno): 44

Vista por consultorio (primeras filas):

,entidad,clues_imb,nombre_de_la_unidad,consultorio,preguntas_esperadas,preguntas_respondidas_validas,faltantes,extras_fuera_catalogo,porcentaje_llenado,lista_faltantes,lista_extras
0,BAJA CALIFORNIA,BCIMB000092,FRACCIONAMIENTO MAR,1,44,30,14,0,68.2,"cinta_metrica, estetoscopio_capsula_doble, mar...",
1,BAJA CALIFORNIA,BCIMB000092,FRACCIONAMIENTO MAR,2,44,30,14,0,68.2,"estadimetro_pediatrico, estetoscopio_capsula_d...",
2,BAJA CALIFORNIA,BCIMB000302,HÉROES DE LA INDEPENDENCIA,1,44,44,0,0,100.0,,
3,BAJA CALIFORNIA,BCIMB000314,VALLE DE LA TRINIDAD,1,44,44,0,0,100.0,,
4,BAJA CALIFORNIA,BCIMB000466,ORIZABA,1,44,2,42,0,4.5,"banco_giratorio, bascula_electronica_con_estad...",

Detalle de faltantes con consultorio (primeras filas):

,entidad,clues_imb,nombre_de_la_unidad,consultorio,pregunta_faltante
0,BAJA CALIFORNIA,BCIMB000092,FRACCIONAMIENTO MAR,1,cinta_metrica
1,BAJA CALIFORNIA,BCIMB000092,FRACCIONAMIENTO MAR,1,estetoscopio_capsula_doble
2,BAJA CALIFORNIA,BCIMB000092,FRACCIONAMIENTO MAR,1,martillo_percusor
3,BAJA CALIFORNIA,BCIMB000092,FRACCIONAMIENTO MAR,1,mesa_de_mayo_de_acero_inoxidable
4,BAJA CALIFORNIA,BCIMB000092,FRACCIONAMIENTO MAR,1,mesa_pasteur

In [ ]:
# Consultorios con >= 90% de llenado
tabla_llenado_90 = tabla_llenado_consultorio[
    tabla_llenado_consultorio["porcentaje_llenado"] >= 80
].reset_index(drop=True)

print(f"Consultorios con >= 90% de llenado: {len(tabla_llenado_90)}")

# Faltantes solo de esos consultorios
clues_cons_90 = tabla_llenado_90[["clues_imb", "consultorio"]]

faltantes_90 = faltantes_por_consultorio.merge(
    clues_cons_90,
    on=["clues_imb", "consultorio"],
    how="inner"
).reset_index(drop=True)

print(f"Registros de faltantes en consultorios >= 90%: {len(faltantes_90)}")

display(tabla_llenado_90)
display(faltantes_90)

Consultorios con >= 90% de llenado: 2046
Registros de faltantes en consultorios >= 90%: 2184

,entidad,clues_imb,nombre_de_la_unidad,consultorio,preguntas_esperadas,preguntas_respondidas_validas,faltantes,extras_fuera_catalogo,porcentaje_llenado,lista_faltantes,lista_extras
0,BAJA CALIFORNIA,BCIMB000302,HÉROES DE LA INDEPENDENCIA,1,44,44,0,0,100.0,,
1,BAJA CALIFORNIA,BCIMB000314,VALLE DE LA TRINIDAD,1,44,44,0,0,100.0,,
2,BAJA CALIFORNIA,BCIMB000536,DURANGO,1,44,44,0,0,100.0,,
3,BAJA CALIFORNIA,BCIMB000990,PEDREGAL DE SANTA JULIA,1,44,44,0,0,100.0,,
4,BAJA CALIFORNIA SUR,BSIMB000013,CENTRO DE SALUD CIUDAD CONSTITUCIÓN,1,44,41,3,0,93.2,"charola_de_mayo_de_acero_inoxidable, contenedo...",
...,...,...,...,...,...,...,...,...,...,...,...
2041,ZACATECAS,ZSIMB002435,CENTRO DE SALUD LA PINTA,2,44,44,0,0,100.0,,
2042,ZACATECAS,ZSIMB002522,CENTRO DE SALUD FRESNILLO 2,1,44,44,0,0,100.0,,
2043,ZACATECAS,ZSIMB002522,CENTRO DE SALUD FRESNILLO 2,2,44,44,0,0,100.0,,
2044,ZACATECAS,ZSIMB002522,CENTRO DE SALUD FRESNILLO 2,3,44,44,0,0,100.0,,
2045,ZACATECAS,ZSIMB002522,CENTRO DE SALUD FRESNILLO 2,4,44,44,0,0,100.0,,

,entidad,clues_imb,nombre_de_la_unidad,consultorio,pregunta_faltante
0,BAJA CALIFORNIA SUR,BSIMB000013,CENTRO DE SALUD CIUDAD CONSTITUCIÓN,1,charola_de_mayo_de_acero_inoxidable
1,BAJA CALIFORNIA SUR,BSIMB000013,CENTRO DE SALUD CIUDAD CONSTITUCIÓN,1,contenedor_rigido_para_rpbi
2,BAJA CALIFORNIA SUR,BSIMB000013,CENTRO DE SALUD CIUDAD CONSTITUCIÓN,1,escritorio_medico
3,BAJA CALIFORNIA SUR,BSIMB000013,CENTRO DE SALUD CIUDAD CONSTITUCIÓN,3,banco_giratorio
4,BAJA CALIFORNIA SUR,BSIMB000030,CENTRO DE SALUD BENITO JUÁREZ,1,bote_sanitario_con_pedal
...,...,...,...,...,...
2179,ZACATECAS,ZSIMB000434,CENTRO DE SALUD COL. TIERRA Y LIBERTAD,1,estetoscopio_pinard_o_doppler_fetal_portatil
2180,ZACATECAS,ZSIMB001402,CENTRO DE SALUD SANTA LUCÍA DE LA SIERRA,1,banco_giratorio
2181,ZACATECAS,ZSIMB001641,CENTRO DE SALUD ZACATECAS,2,estadimetro_pediatrico
2182,ZACATECAS,ZSIMB001641,CENTRO DE SALUD ZACATECAS,4,banco_giratorio
2183,ZACATECAS,ZSIMB001641,CENTRO DE SALUD ZACATECAS,6,espejo_vestidor

In [ ]:
from pathlib import Path
from datetime import date

ruta = Path(fr"C:\Users\{usuario}\Downloads\faltantes_90_{date.today()}.xlsx")
faltantes_90.to_excel(ruta, index=False)
print(f"Archivo guardado en: {ruta}")

Archivo guardado en: C:\Users\jose.valdez\Downloads\faltantes_90_2026-08-06.xlsx

In [ ]:
faltantes_90_agrupado = (
    faltantes_90
    .groupby(["entidad", "clues_imb", "nombre_de_la_unidad", "consultorio"], as_index=False)
    .agg(
        n_faltantes=("pregunta_faltante", "count"),
        preguntas_faltantes=("pregunta_faltante", lambda x: ", ".join(sorted(x))),
    )
    .sort_values(["clues_imb", "consultorio"])
    .reset_index(drop=True)
)

print(f"Filas agrupadas: {len(faltantes_90_agrupado)}")
faltantes_90_agrupado

Filas agrupadas: 710

,entidad,clues_imb,nombre_de_la_unidad,consultorio,n_faltantes,preguntas_faltantes
0,BAJA CALIFORNIA SUR,BSIMB000013,CENTRO DE SALUD CIUDAD CONSTITUCIÓN,1,3,"charola_de_mayo_de_acero_inoxidable, contenedo..."
1,BAJA CALIFORNIA SUR,BSIMB000013,CENTRO DE SALUD CIUDAD CONSTITUCIÓN,3,1,banco_giratorio
2,BAJA CALIFORNIA SUR,BSIMB000030,CENTRO DE SALUD BENITO JUÁREZ,1,2,"bote_sanitario_con_pedal, caja_portalaminilla_..."
3,BAJA CALIFORNIA SUR,BSIMB000071,CENTRO DE SALUD PUERTO SAN CARLOS,1,1,equipo_de_computo
4,BAJA CALIFORNIA SUR,BSIMB000100,CENTRO DE SALUD VILLA MORELOS,1,5,"banco_de_altura, banco_giratorio, estadimetro_..."
...,...,...,...,...,...,...
705,ZACATECAS,ZSIMB000434,CENTRO DE SALUD COL. TIERRA Y LIBERTAD,1,2,"carta_snellen_con_marco, estetoscopio_pinard_o..."
706,ZACATECAS,ZSIMB001402,CENTRO DE SALUD SANTA LUCÍA DE LA SIERRA,1,1,banco_giratorio
707,ZACATECAS,ZSIMB001641,CENTRO DE SALUD ZACATECAS,2,1,estadimetro_pediatrico
708,ZACATECAS,ZSIMB001641,CENTRO DE SALUD ZACATECAS,4,1,banco_giratorio
709,ZACATECAS,ZSIMB001641,CENTRO DE SALUD ZACATECAS,6,1,espejo_vestidor

In [ ]:
# Exportar tabla de faltantes agrupados a public/faltantes.json
faltantes_path = output_dir / "faltantes.json"
faltantes_path.write_text(
    json.dumps(_clean_json(faltantes_90_agrupado), ensure_ascii=False, indent=2),
    encoding="utf-8",
)
print(f"Archivo generado: {faltantes_path}  ({len(faltantes_90_agrupado)} filas)")

Archivo generado: c:\Users\jose.valdez\Downloads\new-form\reporte-new\reporte-_angeles\public\faltantes.json  (710 filas)

In [ ]:
# Unidades con MAYOR cobertura por entidad (top 1 por estado)
# Usando resumen_llenado_clues que tiene porcentaje_llenado_total
top_por_entidad = (
    resumen_llenado_clues
    .sort_values("porcentaje_llenado_total", ascending=False)
    .groupby("entidad", as_index=False)
    .first()[["entidad", "clues_imb", "nombre_de_la_unidad", "consultorios_reportados", "porcentaje_llenado_total"]]
    .sort_values("entidad")
    .reset_index(drop=True)
)

print(f"Entidades representadas: {len(top_por_entidad)}")
display(top_por_entidad.style.background_gradient(
    subset=["porcentaje_llenado_total"], cmap="RdYlGn", vmin=90, vmax=100
))

Entidades representadas: 22

In [ ]:
# Todas las unidades de San Luis Potosí
slp = (
    resumen_llenado_clues[resumen_llenado_clues["entidad"].str.upper().str.contains("SAN LUIS")]
    [["clues_imb", "nombre_de_la_unidad", "consultorios_reportados",
      "preguntas_respondidas_validas_total", "preguntas_esperadas_total",
      "faltantes_total", "porcentaje_llenado_total"]]
    .sort_values("porcentaje_llenado_total", ascending=False)
    .reset_index(drop=True)
)

print(f"Unidades SLP con >=90%: {len(slp)}")
print(f"Promedio llenado: {slp['porcentaje_llenado_total'].mean():.1f}%")
print(f"Consultorios reportados total: {slp['consultorios_reportados'].sum()}")
display(slp)

Unidades SLP con >=90%: 27
Promedio llenado: 94.4%
Consultorios reportados total: 64

,clues_imb,nombre_de_la_unidad,consultorios_reportados,preguntas_respondidas_validas_total,preguntas_esperadas_total,faltantes_total,porcentaje_llenado_total
0,SPIMB000252,PIMIENTA,1,44,44,0,100.0
1,SPIMB000264,COL. JUÁREZ,2,88,88,0,100.0
2,SPIMB000696,SAUCITO,1,44,44,0,100.0
3,SPIMB001331,NUEVO TAMPAON,1,44,44,0,100.0
4,SPIMB000520,CENTRO DE SALUD LOS POCITOS,1,44,44,0,100.0
5,SPIMB000993,PONCIANO ARRIAGA,1,44,44,0,100.0
6,SPIMB000981,CENTRO DE SALUD 1RO. DE MAYO,2,88,88,0,100.0
7,SPIMB002340,CENTRO DE SALUD FRANCISCO VILLA,1,44,44,0,100.0
8,SPIMB002195,CENTRO DE SALUD 6 DE JUNIO,2,88,88,0,100.0
9,SPIMB002101,16 DE SEPTIEMBRE,2,88,88,0,100.0
10,SPIMB001442,LOS LOBOS,1,44,44,0,100.0
11,SPIMB002760,SAN RAFAEL,1,44,44,0,100.0
12,SPIMB002521,CENTRO DE SALUD SIMÓN DÍAZ,1,44,44,0,100.0
13,SPIMB002731,CENTRO DE SALUD LOS MAGUEYES,2,88,88,0,100.0
14,SPIMB002545,CENTRO DE SALUD SAN ANTONIO,1,44,44,0,100.0
15,SPIMB002533,CENTRO DE SALUD BOSQUES DE JACARANDAS,2,88,88,0,100.0
16,SPIMB002830,C.S. URBANO ANÁHUAC,5,219,220,1,99.5
17,SPIMB003146,CENTRO DE SALUD VILLA CACTUS,4,175,176,1,99.4
18,SPIMB002562,CENTRO DE SALUD TERCERAS,4,175,176,1,99.4
19,SPIMB002661,CENTRO DE SALUD JARDINES DE MARIA CECILIA,3,131,132,1,99.2
20,SPIMB000450,PONCIANO ARRIAGA,2,87,88,1,98.9
21,SPIMB002253,CENTRO DE SALUD ROTARIOS,3,130,132,2,98.5
22,SPIMB000445,AURELIO MANRIQUE,1,43,44,1,97.7
23,SPIMB002842,UMF SOLEDAD DE GRACIANO SÁNCHEZ,5,192,220,28,87.3
24,SPIMB000433,PLAN DE IGUALA,1,31,44,13,70.5
25,SPIMB002241,CENTRO DE SALUD DORACELI,3,71,132,61,53.8
26,SPIMB000701,DR. JUAN H. SANCHEZ,11,220,484,264,45.5

In [ ]:
tabla_unidades

,clues,entidad,nombre_de_la_unidad,consultorios,consultorios_habilitados,respondidas,esperadas,porcentaje
762,MCIMB001713,MEXICO,CEAPS SAN MIGUEL CHAPULTEPEC BICENTENARIO,1.0,0.0,2,48.0,100.0
894,MCIMB007243,MEXICO,VALLE DE BRAVO,2.0,0.0,47,96.0,100.0
857,MCIMB006625,MEXICO,CENTRO DE SALUD CARACOLES,2.0,2.0,47,96.0,100.0
818,MCIMB003912,MEXICO,ESTADO DE MÉXICO,6.0,6.0,142,288.0,100.0
809,MCIMB003796,MEXICO,SAN FRANCISCO CUAUTLALPAN,6.0,6.0,143,288.0,100.0
...,...,...,...,...,...,...,...,...
1636,VZIMB008700,VERACRUZ DE IGNACIO DE LA LLAVE,COL. MORELOS,1.0,4.0,48,48.0,100.0
32,BSIMB000363,BAJA CALIFORNIA SUR,CENTRO DE SALUD CON SERVICIOS AMPLIADOS CABO S...,6.0,0.0,432,288.0,100.0
25,BSIMB000235,BAJA CALIFORNIA SUR,"CENTRO DE SALUD LÁZARO CÁRDENAS, LA PAZ",1.0,3.0,49,48.0,100.0
21,BSIMB000182,BAJA CALIFORNIA SUR,CENTRO DE SALUD VILLA ALBERTO A. ALVARADO ARAM...,1.0,2.0,48,48.0,100.0
1645,ZSIMB001332,ZACATECAS,CENTRO DE SALUD AMECA EL VIEJO,1.0,1.0,49,48.0,100.0

## armando

In [ ]:
base_an

,fecha_registro,tipo_registro,entidad,usuario_nombre,usuario_email,clues_imb,categoria_gerencial_ampliada,internet,consultorios_habilitados,consultorio,pregunta,valor,turno,nombre_de_la_unidad
0,28/07/2026 12:35:02,unidad,CAMPECHE,Jesús Antonio Santini Pérez,drsantiniperez@gmail.com,CCIMB000085,NaN,True,7.0,NaN,internet,NaN,NaN,CENTRO DE SALUD DR. WILBERTH ESCALANTE
1,24/07/2026 14:10:57,unidad,HIDALGO,Armando Hernandez Libreros,armando.hernandez@imssbienestar.gob.mx,HGIMB000530,NaN,True,2.0,NaN,internet,NaN,NaN,PROGRESO EL DE ATOTONILCO DE TULA
2,9/07/2026 15:34:57,respuesta,BAJA CALIFORNIA,minelly montoya,minelly@gmail.com,BCIMB000092,NaN,NaN,NaN,1.0,equipo_de_computo_consultorio_1,1,NaN,FRACCIONAMIENTO MAR
3,8/07/2026 12:52:10,respuesta,BAJA CALIFORNIA,minelly montoya,minelly@gmail.com,BCIMB000092,NaN,NaN,NaN,2.0,equipo_de_computo_consultorio_2,1,NaN,FRACCIONAMIENTO MAR
4,8/07/2026 12:52:20,respuesta,BAJA CALIFORNIA,minelly montoya,minelly@gmail.com,BCIMB000092,NaN,NaN,NaN,1.0,banco_de_altura_consultorio_1,1,NaN,FRACCIONAMIENTO MAR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101167,5/08/2026 7:46:06,respuesta,CIUDAD DE MEXICO,Nancy Lopez de Anda,nlopez@sersalud.cdmx.gob.mx,DFIMB000796,NaN,NaN,NaN,1.0,banco_giratorio_consultorio_1,1,NaN,C.S.T-III DR. MANUEL PESQUEIRA
101168,5/08/2026 7:46:45,respuesta,CIUDAD DE MEXICO,Nancy Lopez de Anda,nlopez@sersalud.cdmx.gob.mx,DFIMB000796,NaN,NaN,NaN,1.0,bascula_electronica__con_estadimetro_consultor...,0,NaN,C.S.T-III DR. MANUEL PESQUEIRA
101169,5/08/2026 7:46:29,respuesta,CIUDAD DE MEXICO,Nancy Lopez de Anda,nlopez@sersalud.cdmx.gob.mx,DFIMB000796,NaN,NaN,NaN,1.0,bascula_pesabebes_electronica_consultorio_1,0,NaN,C.S.T-III DR. MANUEL PESQUEIRA
101170,5/08/2026 7:46:42,respuesta,CIUDAD DE MEXICO,Nancy Lopez de Anda,nlopez@sersalud.cdmx.gob.mx,DFIMB000796,NaN,NaN,NaN,1.0,bascula_pesabebes_electronica_consultorio_1,0,NaN,C.S.T-III DR. MANUEL PESQUEIRA
101171,5/08/2026 7:47:05,respuesta,CIUDAD DE MEXICO,Nancy Lopez de Anda,nlopez@sersalud.cdmx.gob.mx,DFIMB000796,NaN,NaN,NaN,1.0,mesa_para_colocar_bascula_pesabebes_consultorio_1,0,NaN,C.S.T-III DR. MANUEL PESQUEIRA

In [ ]:
sus = base_an[base_an["entidad"] == "MEXICO"]

In [ ]:
sus.columns

Index(['fecha_registro', 'tipo_registro', 'entidad', 'usuario_nombre',
       'usuario_email', 'clues_imb', 'categoria_gerencial_ampliada',
       'internet', 'consultorios_habilitados', 'consultorio', 'pregunta',
       'valor', 'turno', 'nombre_de_la_unidad'],
      dtype='object')

In [ ]:
col = ['entidad','clues_imb','nombre_de_la_unidad',]
sus = sus[col]

In [ ]:
claves_manuales = {
    "MCIMB003970",
    "MCIMB003912",
    "NCIMB004040",
    "MCIMB003953",
    "MCIMB002203",
    "MCIMB002191",
    "MCIMB001812",
    "MCIMB003772",
    "MCIMB003796",
    "MCIMB003760",
    "MCIMB000902",
    "MCIMB000984",
    "MCIMB000931",
    "MCIMB009355",
}
sus = (
    sus.drop_duplicates(subset="clues_imb")
    .assign(origen=lambda df: df["clues_imb"].isin(claves_manuales).map({True: "Manual", False: "Subido"}))
    .sort_values(["origen", "clues_imb"], ascending=[False, True])
    .reset_index(drop=True)
)

In [ ]:
sus

    entidad    clues_imb         nombre_de_la_unidad  origen
0    MEXICO  MCIMB000214        SAN PEDRO TEPETITLÁN  Subido
1    MEXICO  MCIMB000692           CINCUENTA ARROBAS  Subido
2    MEXICO  MCIMB000716                PALMAR CHICO  Subido
3    MEXICO  MCIMB000733                  SAN MARTÍN  Subido
4    MEXICO  MCIMB000762           SANTIAGO AMATEPEC  Subido
..      ...          ...                         ...     ...
216  MEXICO  MCIMB003796   SAN FRANCISCO CUAUTLALPAN  Manual
217  MEXICO  MCIMB003912            ESTADO DE MÉXICO  Manual
218  MEXICO  MCIMB003953                      EL SOL  Manual
219  MEXICO  MCIMB003970               BENITO JUÁREZ  Manual
220  MEXICO  MCIMB009355  CENTRO DE SALUD EL POTRERO  Manual

[221 rows x 4 columns]

In [ ]:
from pathlib import Path

ruta = Path.home() / "Downloads" / "EDOMEX.xlsx"

sus.to_excel(ruta, index=False)

print(ruta)

C:\Users\jose.valdez\Downloads\EDOMEX.xlsx

## bommberazo

In [ ]:
clues = pd.read_parquet(fr"C:\Users\{usuario}\IMSS-BIENESTAR\División de Procesamiento de información - Repositorio de Datos\CLUES\clues.parquet")

In [ ]:
catalogo = pd.read_excel(fr"C:\Users\{usuario}\IMSS-BIENESTAR\División de Procesamiento de información - Comando Florence Nightingale\Proyectos\005_Censo\Anterior\Estados duplicados e inconsistencias\Catalogos\Catálogo de Código de Puesto CRH.xlsx")

In [ ]:
bom= pd.read_excel(fr"C:\Users\{usuario}\Downloads\piloto 636.xlsx",sheet_name="Hoja1")

In [ ]:
bom =  bom.drop(columns=['Categoría'])

In [ ]:
tabla_unidades.columns

Index(['clues', 'entidad', 'nombre_de_la_unidad', 'consultorios',
       'consultorios_habilitados', 'respondidas', 'esperadas', 'porcentaje'],
      dtype='object')

In [ ]:
col =['clues', 'entidad', 'consultorios_habilitados','consultorios']
cons= tabla_unidades[col]
cons = cons.rename(columns={
    'clues':'clues_imb',})

In [ ]:
cons_merge = (
    cons[["clues_imb", "consultorios_habilitados", "consultorios"]]

)
bom = bom.merge(cons_merge, on="clues_imb", how="left")
bom["consultorios"] = pd.to_numeric(bom["consultorios"], errors="coerce")
bom["consultorios_habilitados"] = pd.to_numeric(bom["consultorios_habilitados"], errors="coerce")
bom["diferencia"] = bom["consultorios"] - bom["consultorios_habilitados"]

In [ ]:
infra = pd.read_parquet(fr"C:\Users\{usuario}\IMSS-BIENESTAR\División de Procesamiento de información - Repositorio de Datos\Infraestructura\infraestructura.parquet")

In [ ]:
hab_merge = (
    infra[["clues_imb", 'total_consultorios_generales']]

)
bom = bom.merge(hab_merge, on="clues_imb", how="left")

In [ ]:
bom

,clues_imb,nombre_de_la_unidad,consultorios_habilitados,consultorios,diferencia,total_consultorios_generales
0,BCIMB000051,COLONIA LOMA LINDA,0.0,NaN,NaN,6.0
1,BCIMB000092,FRACCIONAMIENTO MAR,0.0,3.0,3.0,3.0
2,BCIMB000162,ISLA DE CEDROS,NaN,NaN,NaN,3.0
3,BCIMB000186,LA MISIÓN,NaN,NaN,NaN,2.0
4,BCIMB000191,REAL DEL CASTILLO,NaN,NaN,NaN,2.0
...,...,...,...,...,...,...
2187,GRIMB010244,CENTRO DE SALUD CON SERVICIOS AMPLIADOS DE CHI...,3.0,1.0,-2.0,5.0
2188,GRIMB010256,CENTRO DE SALUD CON SERVICIOS AMPLIADOS DE HUI...,2.0,1.0,-1.0,2.0
2189,GRIMB010565,CENTRO DE SALUD CON SERVICIOS AMPLIADOS MARQUELIA,NaN,NaN,NaN,3.0
2190,SRIMB001071,CENTRO DE SALUD RURAL MIGUEL ALEMÁN,0.0,4.0,4.0,6.0
2191,TCIMB000704,CESSA VICENTE GUERRERO,NaN,NaN,NaN,6.0

In [ ]:
censo = pd.read_parquet(fr"C:\Users\{usuario}\IMSS-BIENESTAR\División de Procesamiento de información - Datos\Nómina salud\nomina para script\nomina_general.parquet")

In [ ]:
formato = bom

In [ ]:
for_merge = (
    clues[["clues_imb", 'entidad','municipio']]

)
formato = formato.merge(for_merge, on="clues_imb", how="left")

In [ ]:
censo = censo.rename(columns={
    'clues':'clues_imb',})

In [ ]:
#filtro de censo para solo las clues que estan en el formato
censo_filtrado = censo[
    censo["clues_imb"].isin(formato["clues_imb"])
].copy()

In [ ]:
censo_filtrado = censo_filtrado.drop(columns=['clues_imb'])
censo_filtrado = censo_filtrado.rename(columns={
    'clues_trabajando':'clues_imb',})

In [ ]:
censo_filtrado

,entidad,unidad_de_comision,clues_imb,nombre_de_la_unidad,estatus_de_operacion,nivel_atencion,estatus,id_trabajador,nombre_completo,curp,rfc,puesto,codigo_cnpm,codigo_cnpm_26,denominacion_de_puesto,rama,turnos,fuente_de_pago
4724,CAMPECHE,SIN_COMISION,CCIMB000213,CENTRO AVANZADO DE ATENCIÓN PRIMARIA A LA SAL...,EN OPERACION,PRIMER NIVEL,ACTIVO,4998,GARCIA FUENTES LINDA VERONICA,GAFL861022MCCRNN04,GAFL861022KW5,M12008,OP011,OM002,QUIMICA/O (RESPONSABLE DE LABORATORIO),PARAMEDICA,"lunes-matutino, martes-matutino, miercoles-mat...",IMSS BIENESTAR
17974,QUINTANA ROO,SIN_COMISION,QRIMB000952,CENTRO DE SALUD URBANO 09 CANCÚN,EN OPERACION,PRIMER NIVEL,ACTIVO,19025,ANEL DELGADO RUIZ,DERA900624MVZLZN08,DERA900624RI4,M03025,CG014,CG014,ADIMINSTRADOR/A HOSPITAL,CUERPO DE GOBIERNO,"lunes-matutino, martes-matutino, miercoles-mat...",SECRETARIA DE SALUD DEL ESTADO
23876,PUEBLA,SIN_COMISION,PLIMB003810,CENTRO DE SALUD SAN SALVADOR CHACHAPA,EN OPERACION,PRIMER NIVEL,ACTIVO,25042,CRISTINA ORTIZ LUNA,OILC660305MPLRNR08,OILC6603052C5,M13001,OP001,OPELIM001,AUXILIAR ADMINISTRATIVO (GENERAL) ELIMINAR,ELIMINAR,"lunes-matutino, martes-matutino, miercoles-mat...",SECRETARIA DE SALUD DEL ESTADO
28218,GUERRERO,SIN_COMISION,GRIMB003973,R-03 CD. HUITZUCO,EN OPERACION,PRIMER NIVEL,ACTIVO,29482,ALTAMIRANO ARZATE MA. ARISTIDES,AAAA630831MGRLRR03,AAAM630831IG3,M02107,EN002,EN002,ENFERMERA/O DE ATENCION CLINICA,ENFERMERIA,"lunes-matutino, martes-matutino, miercoles-mat...",IMSS BIENESTAR
28219,CIUDAD DE MEXICO,SIN_COMISION,DFIMB000714,C.S.T-III DR. RAFAEL RAMÍREZ SUÁREZ,EN OPERACION,PRIMER NIVEL,ACTIVO,29483,ALMARAZ ALMARAZ ANGELICA MARIA,AAAA680320MDFLLN04,AAAA6803201E1,M02085,OP017,OM007,TRABAJADOR/A SOCIAL,PARAMEDICA,"lunes-matutino, martes-matutino, miercoles-mat...",IMSS BIENESTAR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301278,SINALOA,None,SLIMB000690,CULIACÁN,EN OPERACION,PRIMER NIVEL,ACTIVO,325709,MARCELA RANGEL CORRALES,RACM800718MBCNRR07,RACM800718FX0,M12008,OP011,OM002,QUIMICA/O (RESPONSABLE DE LABORATORIO),PARAMEDICA,"lunes-matutino, martes-matutino, miercoles-mat...",IMSS BIENESTAR
301279,SINALOA,None,SLIMB000690,CULIACÁN,EN OPERACION,PRIMER NIVEL,ACTIVO,325710,FABIOLA ELIZABETH GOMEZ BELTRAN,GOBF940608MSLMLB08,GOBF9406082J8,M12008,OP011,OM002,QUIMICA/O (RESPONSABLE DE LABORATORIO),PARAMEDICA,"lunes-matutino, martes-matutino, miercoles-mat...",IMSS BIENESTAR
301429,SONORA,None,SRIMB000593,CENTRO DE SALUD RURAL CARBO,EN OPERACION,PRIMER NIVEL,ACTIVO,325864,OMAR ALEXIS GUADARRAMA TARAZON,GUTO950911HSRDRM01,GUTO9509113V2,CFK2100001,CG001,CG001,DIRECTOR/A HOSPITAL,CUERPO DE GOBIERNO,"lunes-matutino, martes-matutino, miercoles-mat...",SECRETARIA DE SALUD FEDERAL
301622,SONORA,None,SRIMB001416,CENTRO DE SALUD URBANO NAVOJOA,EN OPERACION,PRIMER NIVEL,ACTIVO,326057,ROSA MARIA ONTIVEROS DORAME,OIDR841106MSRNRS04,OIDR8411064H4,M02036,ME056,ME056,ESPECIALISTA EN INMUNOLOGIA CLINICA Y ALERGIA,MEDICOS ESPECIALISTAS,"lunes-matutino, martes-matutino, miercoles-mat...",SECRETARIA DE SALUD DEL ESTADO
301644,PUEBLA,None,PLIMB001903,CENTRO DE SALUD URBANO LA POPULAR CASTILLOTLA,EN OPERACION,PRIMER NIVEL,LICENCIA SIN GOCE DE SUELDO,326079,BETHZAIDA FERNANDEZ CANEDA,FECB850703MPLRNT08,FECB850703158,M01006,MG001,MG001,MEDICA/O GENERAL,MEDICINA GENERAL,"lunes-matutino, martes-matutino, miercoles-mat...",IMSS BIENESTAR

In [ ]:
# Agrupar censo_filtrado por entidad, clues_imb y rama con suma de turnos
cols_group = ["entidad", "clues_imb", "rama"]
faltantes = [c for c in cols_group + ["turnos"] if c not in censo_filtrado.columns]
if faltantes:
    raise KeyError(f"Faltan columnas en censo_filtrado: {faltantes}")

tmp = censo_filtrado.copy()
for c in cols_group:
    tmp[c] = tmp[c].astype(str).str.strip()

# Guardar version textual de turnos por fila
tmp["turnos_texto_fila"] = (
    tmp["turnos"]
    .fillna("")
    .astype(str)
    .str.lower()
    .str.split(",")
    .apply(lambda xs: ", ".join(sorted({x.strip() for x in xs if x and x.strip()})))
)

# Guardar fuente_de_pago en texto por fila (si existe)
if "fuente_de_pago" in tmp.columns:
    tmp["fuente_de_pago_texto"] = (
        tmp["fuente_de_pago"]
        .fillna("")
        .astype(str)
        .str.strip()
    )
else:
    tmp["fuente_de_pago_texto"] = ""

# 1) Intentar tratar turnos como numerico
turnos_num = pd.to_numeric(tmp["turnos"], errors="coerce")

if turnos_num.notna().any():
    tmp["turnos_num"] = turnos_num.fillna(0)
else:
    # 2) Si turnos viene como texto tipo "lunes-matutino, martes-matutino",
    # contar turnos unicos por fila
    tmp["turnos_num"] = (
        tmp["turnos"]
        .fillna("")
        .astype(str)
        .str.lower()
        .str.split(",")
        .apply(lambda xs: len({x.strip() for x in xs if x and x.strip()}))
    )

# Evitar duplicados por persona-turno antes de sumar
persona_col = next((c for c in ["rfc", "curp", "matricula", "id_personal", "nombre"] if c in tmp.columns), None)
if persona_col:
    dedup_cols = cols_group + [persona_col, "turnos_texto_fila", "fuente_de_pago_texto"]
else:
    dedup_cols = cols_group + ["turnos_texto_fila", "fuente_de_pago_texto"]

tmp_unico = tmp.drop_duplicates(subset=dedup_cols)

censo_agrupado = (
    tmp_unico
    .groupby(cols_group, as_index=False)
    .agg(
        turnos=("turnos_num", "sum"),
        turnos_escritos=(
            "turnos_texto_fila",
            lambda s: ", ".join(
                sorted({
                    tok.strip()
                    for val in s
                    for tok in str(val).split(",")
                    if tok and tok.strip()
                })
            ),
        ),
        fuente_de_pago=(
            "fuente_de_pago_texto",
            lambda s: ", ".join(sorted({v.strip() for v in s if str(v).strip()})),
        ),
        registros=("turnos_num", "size"),
    )
    .sort_values(cols_group)
    .reset_index(drop=True)
)

In [ ]:
# Consolidar ramas médicas en una sola categoría: MEDICINA
ramas_medicina = [
    "MEDICINA GENERAL",
    "MEDICOS ESPECIALISTAS",
    "MEDICINA TRADICIONAL",
]

# Mantener solo ramas de interés
censo_agrupado = censo_agrupado[
    censo_agrupado["rama"].isin(["ENFERMERIA", *ramas_medicina])
] .copy()

# Filas no médicas (por ahora solo ENFERMERIA)
no_medicina = censo_agrupado[~censo_agrupado["rama"].isin(ramas_medicina)].copy()

# Filas médicas consolidadas
medicina = (
    censo_agrupado[censo_agrupado["rama"].isin(ramas_medicina)]
    .assign(rama="MEDICINA")
    .groupby(["entidad", "clues_imb", "rama"], as_index=False)
    .agg(
        turnos=("turnos", "sum"),
        turnos_escritos=(
            "turnos_escritos",
            lambda s: ", ".join(
                sorted({
                    tok.strip()
                    for val in s
                    for tok in str(val).split(",")
                    if tok and tok.strip()
                })
            ),
        ),
        fuente_de_pago=(
            "fuente_de_pago",
            lambda s: ", ".join(sorted({v.strip() for v in s if str(v).strip()})),
        ),
        registros=("registros", "sum"),
    )
)

# Resultado final
censo_agrupado = (
    pd.concat([no_medicina, medicina], ignore_index=True)
    .sort_values(["entidad", "clues_imb", "rama"])
.reset_index(drop=True)
)

In [ ]:
censo_agrupado

,entidad,clues_imb,rama,turnos,turnos_escritos,fuente_de_pago,registros
0,BAJA CALIFORNIA,BCIMB000051,ENFERMERIA,15,"jueves-matutino, lunes-matutino, martes-matuti...","EXINSABI, IMSS BIENESTAR, OTRO",3
1,BAJA CALIFORNIA,BCIMB000051,MEDICINA,20,"domingo-matutino, jueves-matutino, lunes-matut...","IMSS BIENESTAR, OTRO",4
2,BAJA CALIFORNIA,BCIMB000063,ENFERMERIA,15,"jueves-matutino, lunes-matutino, martes-matuti...","EXINSABI, IMSS BIENESTAR, OTRO",3
3,BAJA CALIFORNIA,BCIMB000063,MEDICINA,15,"jueves-matutino, lunes-matutino, martes-matuti...","EXINSABI, IMSS BIENESTAR, OTRO",3
4,BAJA CALIFORNIA,BCIMB000075,ENFERMERIA,30,"jueves-matutino, lunes-matutino, martes-matuti...","IMSS BIENESTAR, OTRO, SECRETARIA DE SALUD FEDERAL",6
...,...,...,...,...,...,...,...
4023,ZACATECAS,ZSIMB002435,ENFERMERIA,15,"jueves-matutino, lunes-matutino, martes-matuti...","IMSS BIENESTAR, SECRETARIA DE SALUD DEL ESTADO",3
4024,ZACATECAS,ZSIMB002435,MEDICINA,10,"domingo-matutino, jueves-matutino, jueves-mixt...","IMSS BIENESTAR, SECRETARIA DE SALUD DEL ESTADO",2
4025,ZACATECAS,ZSIMB002481,ENFERMERIA,5,"jueves-matutino, lunes-matutino, martes-matuti...",IMSS BIENESTAR,1
4026,ZACATECAS,ZSIMB002522,ENFERMERIA,20,"jueves-matutino, jueves-vespertino, lunes-matu...",SECRETARIA DE SALUD DEL ESTADO,4
4027,ZACATECAS,ZSIMB002522,MEDICINA,39,"domingo-jornada acumulada, jueves-matutino, lu...","IMSS BIENESTAR, SECRETARIA DE SALUD DEL ESTADO",9

In [ ]:
# Pivotear rama para tener columnas por rama y sus datos
censo_pivot = censo_agrupado.pivot_table(
    index=["entidad", "clues_imb"],
    columns="rama",
    values=["turnos", "turnos_escritos", "fuente_de_pago", "registros"],
    aggfunc="first",
)

# Aplanar nombres de columnas
censo_pivot.columns = [f"{metrica}_{rama}" for metrica, rama in censo_pivot.columns]
censo_pivot = censo_pivot.reset_index()

# Rellenar nulos segun tipo de columna
for col in censo_pivot.columns:
    if col.startswith(("turnos_escritos_", "fuente_de_pago_")):
        censo_pivot[col] = censo_pivot[col].fillna("")
    elif col.startswith(("turnos_", "registros_")):
        censo_pivot[col] = pd.to_numeric(censo_pivot[col], errors="coerce").fillna(0)

# Homologacion de turnos: quitar dia y conservar solo turno
def homologar_turnos(texto):
    tokens = [t.strip().lower() for t in str(texto).split(",") if t and t.strip()]

    categorias = set()
    for t in tokens:
        if "matutino" in t:
            categorias.add("Matutino")
        elif "vespertino" in t:
            categorias.add("Vespertino")
        elif "nocturno" in t:
            categorias.add("Nocturno")
        elif "jornadaacumulada" in t or "jornada acumulada" in t:
            categorias.add("Jornada acumulada")

    salida = []
    if "Matutino" in categorias and "Vespertino" in categorias:
        salida.append("Ambos")
        categorias.discard("Matutino")
        categorias.discard("Vespertino")
    else:
        if "Matutino" in categorias:
            salida.append("Matutino")
        if "Vespertino" in categorias:
            salida.append("Vespertino")

    if "Nocturno" in categorias:
        salida.append("Nocturno")
    # Jornada acumulada se conserva en el dato original, pero no se muestra en homologados

    return ", ".join(salida)

for col in [c for c in censo_pivot.columns if c.startswith("turnos_escritos_")]:
    rama = col.replace("turnos_escritos_", "")
    censo_pivot[f"turnos_homologados_{rama}"] = censo_pivot[col].apply(homologar_turnos)

censo_pivot.head()

,entidad,clues_imb,fuente_de_pago_ENFERMERIA,fuente_de_pago_MEDICINA,registros_ENFERMERIA,registros_MEDICINA,turnos_ENFERMERIA,turnos_MEDICINA,turnos_escritos_ENFERMERIA,turnos_escritos_MEDICINA,turnos_homologados_ENFERMERIA,turnos_homologados_MEDICINA
0,BAJA CALIFORNIA,BCIMB000051,"EXINSABI, IMSS BIENESTAR, OTRO","IMSS BIENESTAR, OTRO",3.0,4.0,15.0,20.0,"jueves-matutino, lunes-matutino, martes-matuti...","domingo-matutino, jueves-matutino, lunes-matut...",Matutino,Matutino
1,BAJA CALIFORNIA,BCIMB000063,"EXINSABI, IMSS BIENESTAR, OTRO","EXINSABI, IMSS BIENESTAR, OTRO",3.0,3.0,15.0,15.0,"jueves-matutino, lunes-matutino, martes-matuti...","jueves-matutino, lunes-matutino, martes-matuti...",Matutino,Matutino
2,BAJA CALIFORNIA,BCIMB000075,"IMSS BIENESTAR, OTRO, SECRETARIA DE SALUD FEDERAL","IMSS BIENESTAR, SECRETARIA DE SALUD FEDERAL",6.0,3.0,30.0,15.0,"jueves-matutino, lunes-matutino, martes-matuti...","jueves-matutino, lunes-matutino, martes-matuti...",Matutino,Matutino
3,BAJA CALIFORNIA,BCIMB000080,,"IMSS BIENESTAR, OTRO",0.0,2.0,0.0,7.0,,"domingo-otro, jueves-matutino, lunes-matutino,...",,Matutino
4,BAJA CALIFORNIA,BCIMB000092,EXINSABI,"IMSS BIENESTAR, OTRO",1.0,3.0,5.0,15.0,"jueves-matutino, lunes-matutino, martes-matuti...","domingo-matutino, jueves-matutino, lunes-matut...",Matutino,Matutino

In [ ]:
cens_merge = (
    censo_pivot[[
        "clues_imb",
        "fuente_de_pago_ENFERMERIA",
        "fuente_de_pago_MEDICINA",
        "registros_ENFERMERIA",
        "registros_MEDICINA",
        "turnos_ENFERMERIA",
        "turnos_MEDICINA",
        "turnos_escritos_ENFERMERIA",
        "turnos_escritos_MEDICINA",
        "turnos_homologados_ENFERMERIA",
        "turnos_homologados_MEDICINA",
    ]]
)

cols_censo = [c for c in cens_merge.columns if c != "clues_imb"]
cols_si_no = [
    "cuenta_con_personal_medicina",
    "cuenta_con_personal_enfermeria",
]

# Evita columnas duplicadas si esta celda se ejecuta más de una vez
formato = formato.drop(columns=[c for c in (cols_censo + cols_si_no) if c in formato.columns], errors="ignore")
formato = formato.merge(cens_merge, on="clues_imb", how="left")

formato["registros_ENFERMERIA"] = pd.to_numeric(formato["registros_ENFERMERIA"], errors="coerce").fillna(0)
formato["registros_MEDICINA"] = pd.to_numeric(formato["registros_MEDICINA"], errors="coerce").fillna(0)

formato["cuenta_con_personal_enfermeria"] = formato["registros_ENFERMERIA"].gt(0).map({True: "si", False: "no"})
formato["cuenta_con_personal_medicina"] = formato["registros_MEDICINA"].gt(0).map({True: "si", False: "no"})

In [ ]:
columnas = [
    "clues_imb",
    "nombre_de_la_unidad",
    "entidad",
    "municipio",
    "registros_MEDICINA",
    "turnos_homologados_MEDICINA",
    "fuente_de_pago_MEDICINA",
    "registros_ENFERMERIA",
    "turnos_homologados_ENFERMERIA",
    "fuente_de_pago_ENFERMERIA",
]
formato = formato[columnas]

In [ ]:
formato

,clues_imb,nombre_de_la_unidad,entidad,municipio,registros_MEDICINA,turnos_homologados_MEDICINA,fuente_de_pago_MEDICINA,registros_ENFERMERIA,turnos_homologados_ENFERMERIA,fuente_de_pago_ENFERMERIA
0,BCIMB000051,COLONIA LOMA LINDA,BAJA CALIFORNIA,ENSENADA,4.0,Matutino,"IMSS BIENESTAR, OTRO",3.0,Matutino,"EXINSABI, IMSS BIENESTAR, OTRO"
1,BCIMB000092,FRACCIONAMIENTO MAR,BAJA CALIFORNIA,ENSENADA,3.0,Matutino,"IMSS BIENESTAR, OTRO",1.0,Matutino,EXINSABI
2,BCIMB000162,ISLA DE CEDROS,BAJA CALIFORNIA,ENSENADA,2.0,Matutino,IMSS BIENESTAR,2.0,Matutino,"EXINSABI, SECRETARIA DE SALUD DEL ESTADO"
3,BCIMB000186,LA MISIÓN,BAJA CALIFORNIA,ENSENADA,2.0,Matutino,"EXINSABI, IMSS BIENESTAR",2.0,Matutino,IMSS BIENESTAR
4,BCIMB000191,REAL DEL CASTILLO,BAJA CALIFORNIA,ENSENADA,2.0,Matutino,"EXINSABI, IMSS BIENESTAR",2.0,Matutino,"EXINSABI, IMSS BIENESTAR"
...,...,...,...,...,...,...,...,...,...,...
2187,GRIMB010244,CENTRO DE SALUD CON SERVICIOS AMPLIADOS DE CHI...,GUERRERO,LEONARDO BRAVO,5.0,"Matutino, Nocturno","IMSS BIENESTAR, SECRETARIA DE SALUD DEL ESTADO",14.0,"Ambos, Nocturno","IMSS BIENESTAR, OTRO, SECRETARIA DE SALUD DEL ..."
2188,GRIMB010256,CENTRO DE SALUD CON SERVICIOS AMPLIADOS DE HUI...,GUERRERO,EDUARDO NERI,0.0,NaN,NaN,0.0,NaN,NaN
2189,GRIMB010565,CENTRO DE SALUD CON SERVICIOS AMPLIADOS MARQUELIA,GUERRERO,MARQUELIA,0.0,NaN,NaN,0.0,NaN,NaN
2190,SRIMB001071,CENTRO DE SALUD RURAL MIGUEL ALEMÁN,SONORA,HERMOSILLO,9.0,"Matutino, Nocturno","IMSS BIENESTAR, SECRETARIA DE SALUD DEL ESTADO",14.0,"Ambos, Nocturno","IMSS BIENESTAR, SECRETARIA DE SALUD DEL ESTADO"
2191,TCIMB000704,CESSA VICENTE GUERRERO,TABASCO,CENTLA,21.0,"Ambos, Nocturno","IMSS BIENESTAR, SECRETARIA DE SALUD DEL ESTADO...",17.0,"Ambos, Nocturno","IMSS BIENESTAR, SECRETARIA DE SALUD DEL ESTADO..."

In [ ]:
dup_mask = formato["clues_imb"].astype(str).str.strip().duplicated(keep=False)
duplicados = (
    formato.loc[dup_mask, ["clues_imb"]]
    .value_counts()
    .reset_index(name="repeticiones")
    .sort_values(["repeticiones", "clues_imb"], ascending=[False, True])
)

print(f"Filas en formato: {len(formato)}")
print(f"CLUES únicas: {formato['clues_imb'].astype(str).str.strip().nunique()}")
print(f"CLUES duplicadas: {len(duplicados)}")

duplicados.head(20)

Filas en formato: 2192
CLUES únicas: 2191
CLUES duplicadas: 1

     clues_imb  repeticiones
0  QRIMB000491             2

In [ ]:
formato = formato.drop_duplicates()

In [ ]:
formato.columns

Index(['clues_imb', 'nombre_de_la_unidad', 'entidad', 'municipio',
       'registros_MEDICINA', 'turnos_homologados_MEDICINA',
       'fuente_de_pago_MEDICINA', 'registros_ENFERMERIA',
       'turnos_homologados_ENFERMERIA', 'fuente_de_pago_ENFERMERIA'],
      dtype='object')

In [ ]:
import os

ruta_descargas = os.path.join(
    "C:\\Users",
    os.getlogin(),
    "Downloads",
    "consultorios_comparacion.xlsx"
)

bom.to_excel(ruta_descargas, index=False)