In [471]:
import pandas as pd
import os
usuario = os.getlogin()

In [472]:
import pandas as pd


base_an = pd.read_csv(fr"C:\Users\{usuario}\Downloads\nuevo-inf\informe--de-ang\base_an.csv")

In [473]:
base = pd.read_excel(fr"C:\Users\{usuario}\Downloads\nuevo-f\formulario-ang\bases\UnidadesIMB_CS!_v2.xlsx",sheet_name="Sheet 1")
clues = pd.read_parquet(fr"C:\Users\{usuario}\IMSS-BIENESTAR\División de Procesamiento de información - Repositorio de Datos\CLUES\clues.parquet")

In [474]:
base_an = base_an.drop(columns=["nombre_de_la_unidad"])

In [475]:
base_an

,fecha_registro,tipo_registro,entidad,usuario_nombre,usuario_email,clues_imb,categoria_gerencial_ampliada,internet,consultorios_habilitados,consultorio,pregunta,valor,turno
0,15/07/2026 20:33:13,unidad,CAMPECHE,Jesús Antonio Santini Pérez,drsantiniperez@gmail.com,CCIMB000085,NaN,True,7.0,NaN,internet,NaN,NaN
1,17/07/2026 11:28:26,unidad,HIDALGO,Armando Hernandez Libreros,armando.hernandez@imssbienestar.gob.mx,HGIMB000530,NaN,True,2.0,NaN,internet,NaN,NaN
2,9/07/2026 15:34:57,respuesta,BAJA CALIFORNIA,minelly montoya,minelly@gmail.com,BCIMB000092,NaN,NaN,NaN,1.0,equipo_de_computo_consultorio_1,1,NaN
3,8/07/2026 12:52:10,respuesta,BAJA CALIFORNIA,minelly montoya,minelly@gmail.com,BCIMB000092,NaN,NaN,NaN,2.0,equipo_de_computo_consultorio_2,1,NaN
4,8/07/2026 12:52:20,respuesta,BAJA CALIFORNIA,minelly montoya,minelly@gmail.com,BCIMB000092,NaN,NaN,NaN,1.0,banco_de_altura_consultorio_1,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
71913,23/07/2026 11:39:59,respuesta,MICHOACAN DE OCAMPO,MARCO ANTONIO RANGEL MARQUEZ,markorm11@hotmail.com,MNIMB001526,NaN,NaN,NaN,5.0,turno_consultorio_5,Vespertino,NaN
71914,23/07/2026 11:40:03,respuesta,MICHOACAN DE OCAMPO,MARCO ANTONIO RANGEL MARQUEZ,markorm11@hotmail.com,MNIMB001526,NaN,NaN,NaN,6.0,turno_consultorio_6,Vespertino,NaN
71915,23/07/2026 11:40:03,respuesta,MICHOACAN DE OCAMPO,MARCO ANTONIO RANGEL MARQUEZ,markorm11@hotmail.com,MNIMB001526,NaN,NaN,NaN,4.0,turno_consultorio_4,Vespertino,NaN
71916,23/07/2026 11:40:08,respuesta,MEXICO,Erika Nuñez Castro,sanlorenzocuauhtenco4@gmail.com,MCIMB001276,NaN,NaN,NaN,1.0,equipo_de_computo_consultorio_1,2,NaN
71917,23/07/2026 11:40:10,respuesta,MEXICO,Erika Nuñez Castro,sanlorenzocuauhtenco4@gmail.com,MCIMB001276,NaN,NaN,NaN,1.0,banco_de_altura_consultorio_1,2,NaN

In [476]:
base_an.columns.tolist()

['fecha_registro',
 'tipo_registro',
 'entidad',
 'usuario_nombre',
 'usuario_email',
 'clues_imb',
 'categoria_gerencial_ampliada',
 'internet',
 'consultorios_habilitados',
 'consultorio',
 'pregunta',
 'valor',
 'turno']

In [477]:
col = ["clues_imb"]
base = base[col]

In [478]:
base

        clues_imb
0     BCIMB000051
1     BCIMB000092
2     BCIMB000162
3     BCIMB000186
4     BCIMB000191
...           ...
2822  GRIMB010244
2823  GRIMB010256
2824  GRIMB010565
2825  SRIMB001071
2826  TCIMB000704

[2827 rows x 1 columns]

In [479]:
base = base.merge(
    clues[["clues_imb", "entidad",'nombre_de_la_unidad']],
    on="clues_imb",
    how="left"
)

In [480]:
base_an = base_an.merge(
    clues[["clues_imb",'nombre_de_la_unidad']],
    on="clues_imb",
    how="left"
)

In [481]:
b = pd.read_excel(fr"C:\Users\{usuario}\Downloads\nuevo-f\formulario-ang\bases\UM_IMB_SUS.xlsx",sheet_name="Hoja2")

In [482]:
b = b.drop(index=[3])
b = b.drop(columns=['Unnamed: 1'])
b = b.rename(columns={
   'CLUES' : 'preguntas',
})

In [483]:
base_an

,fecha_registro,tipo_registro,entidad,usuario_nombre,usuario_email,clues_imb,categoria_gerencial_ampliada,internet,consultorios_habilitados,consultorio,pregunta,valor,turno,nombre_de_la_unidad
0,15/07/2026 20:33:13,unidad,CAMPECHE,Jesús Antonio Santini Pérez,drsantiniperez@gmail.com,CCIMB000085,NaN,True,7.0,NaN,internet,NaN,NaN,CENTRO DE SALUD DR. WILBERTH ESCALANTE
1,17/07/2026 11:28:26,unidad,HIDALGO,Armando Hernandez Libreros,armando.hernandez@imssbienestar.gob.mx,HGIMB000530,NaN,True,2.0,NaN,internet,NaN,NaN,PROGRESO EL DE ATOTONILCO DE TULA
2,9/07/2026 15:34:57,respuesta,BAJA CALIFORNIA,minelly montoya,minelly@gmail.com,BCIMB000092,NaN,NaN,NaN,1.0,equipo_de_computo_consultorio_1,1,NaN,FRACCIONAMIENTO MAR
3,8/07/2026 12:52:10,respuesta,BAJA CALIFORNIA,minelly montoya,minelly@gmail.com,BCIMB000092,NaN,NaN,NaN,2.0,equipo_de_computo_consultorio_2,1,NaN,FRACCIONAMIENTO MAR
4,8/07/2026 12:52:20,respuesta,BAJA CALIFORNIA,minelly montoya,minelly@gmail.com,BCIMB000092,NaN,NaN,NaN,1.0,banco_de_altura_consultorio_1,1,NaN,FRACCIONAMIENTO MAR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71913,23/07/2026 11:39:59,respuesta,MICHOACAN DE OCAMPO,MARCO ANTONIO RANGEL MARQUEZ,markorm11@hotmail.com,MNIMB001526,NaN,NaN,NaN,5.0,turno_consultorio_5,Vespertino,NaN,CENTRO DE SALUD MORELIA (DR. JUAN MANUEL GONZÁ...
71914,23/07/2026 11:40:03,respuesta,MICHOACAN DE OCAMPO,MARCO ANTONIO RANGEL MARQUEZ,markorm11@hotmail.com,MNIMB001526,NaN,NaN,NaN,6.0,turno_consultorio_6,Vespertino,NaN,CENTRO DE SALUD MORELIA (DR. JUAN MANUEL GONZÁ...
71915,23/07/2026 11:40:03,respuesta,MICHOACAN DE OCAMPO,MARCO ANTONIO RANGEL MARQUEZ,markorm11@hotmail.com,MNIMB001526,NaN,NaN,NaN,4.0,turno_consultorio_4,Vespertino,NaN,CENTRO DE SALUD MORELIA (DR. JUAN MANUEL GONZÁ...
71916,23/07/2026 11:40:08,respuesta,MEXICO,Erika Nuñez Castro,sanlorenzocuauhtenco4@gmail.com,MCIMB001276,NaN,NaN,NaN,1.0,equipo_de_computo_consultorio_1,2,NaN,SAN LORENZO CUAUHTENCO
71917,23/07/2026 11:40:10,respuesta,MEXICO,Erika Nuñez Castro,sanlorenzocuauhtenco4@gmail.com,MCIMB001276,NaN,NaN,NaN,1.0,banco_de_altura_consultorio_1,2,NaN,SAN LORENZO CUAUHTENCO

In [484]:
b

                                            preguntas
0                                 Nombre de la Unidad
1                  Consultorios generales habilitados
2                  Consultorios generales disponibles
4                                   Equipo de cómputo
5                                            Internet
6                                     Banco de altura
7                                     Banco giratorio
8                Báscula electrónica  con estadímetro
9                      Báscula pesabebés electrónica
10                Mesa para colocar báscula pesabebés
11                           Bote sanitario con pedal
12    Caja portalaminilla de plástico con separadores
13                            Carta Snellen con marco
14                Charola de Mayo de acero inoxidable
15                                      Cinta métrica
16                        Contenedor de jabón líquido
17                  Contenedor de toallas desechables
18                        Contenedor rígido para RPBI
19                 Cubeta de acero inoxidable y bolsa
20                                  Escritorio médico
21                                  Esfigmomanómetro
22                                    Espejo vestidor
23                                 Espejos vaginales
24                             Estadímetro pediátrico
25                         Estetoscopio cápsula doble
26       Estetoscopio Pinard o doppler fetal portátil
27  Guarda de medicamentos, materiales o instrumental
28                           Guardarropa con perchero
29             Lámpara de examinación  de pie rodable
30                                            Lavabo
31                                  Martillo percusor
32                   Mesa de Mayo de acero inoxidable
33                                       Mesa Pasteur
34                    Mesa universal para Exploración
35                                          Otoscopio
36                                 Oximetro de pulso
37        Porta cubeta rodable con protector de hule
38             Porta rollo para papel Kraft o sábanas
39                             Silla para el paciente
40                          Silla para el acompañante
41                  Sillón giratorio de respaldo bajo
42  Termo congelante integrado para transporte y c...
43                  Paquetes refrigerantes para termo
44                              Termómetro de vástago
45                                Termómetro digital
46                                       Tijera recta
47             Torundera con tapa de acero Inoxidable
48                        Vaso contenedor  de vacunas

## porcentaje

In [485]:
# TABLA 2 - COMPLETITUD POR UNIDAD

# Número de preguntas del formulario
n_preguntas = len(b)

# Número de consultorios por unidad
consultorios = (
    base_an
    .groupby(["clues_imb","entidad",'nombre_de_la_unidad'],as_index=False)
    ["consultorio"]
    .max()
)

consultorios.rename(
    columns={"consultorio":"consultorios"},
    inplace=True
)

# Preguntas respondidas
respondidas = (
    base_an
    .groupby(["clues_imb","entidad",'nombre_de_la_unidad'])
    .size()
    .reset_index(name="respondidas")
)

tabla_unidades = consultorios.merge(
    respondidas,
    on=["clues_imb","entidad",'nombre_de_la_unidad']
)

tabla_unidades["esperadas"] = (
    tabla_unidades["consultorios"]
    * n_preguntas
)

tabla_unidades["porcentaje"] = (
    tabla_unidades["respondidas"]
    / tabla_unidades["esperadas"]
    *100
).round(1).clip(upper=100)

tabla_unidades = (
    tabla_unidades
    .rename(columns={"clues_imb":"clues"})
    .sort_values("porcentaje")
)

In [486]:
tabla_unidades = tabla_unidades[tabla_unidades["porcentaje"] >= 90]

In [487]:
tabla_unidades.head()

,clues,entidad,nombre_de_la_unidad,consultorios,respondidas,esperadas,porcentaje
631,MCIMB004064,MEXICO,LOS PIRULES,8.0,346,384.0,90.1
242,GRIMB003524,GUERRERO,R-01 CUACOYULILLO,2.0,87,96.0,90.6
211,GRIMB002882,GUERRERO,CENTRO DE SALUD CUALAC,2.0,87,96.0,90.6
1070,TCIMB001853,TABASCO,CENTRO DE SALUD CON DOS NUCLEOS BASICOS CHABLE...,2.0,87,96.0,90.6
584,MCIMB002034,MEXICO,MIGUEL HIDALGO,2.0,87,96.0,90.6

## por unidades

In [488]:
import pandas as pd

# Información de la unidad
unidad = (
    base_an[base_an["tipo_registro"] == "unidad"][
        [
            "entidad",
            "clues_imb",
            "nombre_de_la_unidad",
            "internet",
            "consultorios_habilitados",
        ]
    ]
    .drop_duplicates("clues_imb")
)

# Información por consultorio
respuesta = base_an[base_an["tipo_registro"] == "respuesta"].copy()

# Quitar el sufijo _1, _2, _3...
respuesta["pregunta"] = respuesta["pregunta"].str.replace(
    r"_\d+$", "", regex=True
)

# Convertir preguntas en columnas
pivot = respuesta.pivot_table(
    index=["entidad", "clues_imb", "consultorio"],
    columns="pregunta",
    values="valor",
    aggfunc="first"
).reset_index()

pivot.columns.name = None

# Unir con la información de la unidad
resultado = pivot.merge(
    unidad,
    on=["entidad", "clues_imb"],
    how="left"
)

# Reordenar columnas
columnas_fijas = [
    "entidad",
    "clues_imb",
    "nombre_de_la_unidad",
    "internet",
    "consultorios_habilitados",
    "consultorio",
]

columnas_preguntas = [
    c for c in resultado.columns if c not in columnas_fijas
]

resultado = resultado[columnas_fijas + sorted(columnas_preguntas)]

In [489]:
# Filtrar resultado: solo CLUES con >= 90% de respuestas (tabla_unidades)
clues_filtradas = set(tabla_unidades["clues"])
resultado = resultado[resultado["clues_imb"].isin(clues_filtradas)].reset_index(drop=True)
print(f"Filas tras filtro (>=90%): {len(resultado)}  |  CLUES únicas: {resultado['clues_imb'].nunique()}")

Filas tras filtro (>=90%): 1162  |  CLUES únicas: 793

In [490]:
clues.columns

Index(['clues_imb', 'clues_ssa_y_sme', 'categoria_gerencial_uas',
       'categoria_gerencial', 'categoria_gerencial_ampliada',
       'clave_de_la_entidad', 'entidad', 'clave_del_municipio', 'municipio',
       'localidad', 'clave_de_la_localidad', 'nombre_de_la_unidad',
       'nombre_comercial', 'estatus_de_operacion', 'nivel_atencion',
       'clave_de_tipologia', 'nombre_de_tipologia', 'clave_de_subtipologia',
       'nombre_de_subtipologia', 'estrato_unidad', 'cve_ro', 'nombre_region',
       'latitud', 'longitud', 'organ_ro', 'tipo_hbc'],
      dtype='object')

In [491]:
resultado = resultado.merge(
    clues[["entidad", "clues_imb", "latitud", "longitud"]],
    on=["entidad", "clues_imb"],
    how="left"
)

In [492]:
resultado.columns

Index(['entidad', 'clues_imb', 'nombre_de_la_unidad', 'internet',
       'consultorios_habilitados', 'consultorio',
       'banco_de_altura_consultorio', 'banco_giratorio_consultorio',
       'bascula_electronica__con_estadimetro_consultorio',
       'bascula_pesabebes_electronica_consultorio',
       'bote_sanitario_con_pedal_consultorio',
       'caja_portalaminilla_de_plastico_con_separadores_consultorio',
       'carta_snellen_con_marco_consultorio',
       'charola_de_mayo_de_acero_inoxidable_consultorio',
       'cinta_metrica_consultorio', 'contenedor_de_jabon_liquido_consultorio',
       'contenedor_de_toallas_desechables_consultorio',
       'contenedor_rigido_para_rpbi_consultorio',
       'cubeta_de_acero_inoxidable_y_bolsa_consultorio',
       'equipo_de_computo_consultorio', 'escritorio_medico_consultorio',
       'esfigmomanometro_consultorio', 'espejo_vestidor_consultorio',
       'espejos_vaginales_consultorio', 'estadimetro_pediatrico_consultorio',
       'estetoscopio_capsula_doble_consultorio',
       'estetoscopio_pinard_o_doppler_fetal_portatil_consultorio',
       'guarda_de_medicamentos,_materiales_o_instrumental_consultorio',
       'guardarropa_con_perchero_consultorio',
       'lampara_de_examinacion__de_pie_rodable_consultorio',
       'lavabo_consultorio', 'martillo_percusor_consultorio',
       'mesa_de_mayo_de_acero_inoxidable_consultorio',
       'mesa_para_colocar_bascula_pesabebes_consultorio',
       'mesa_pasteur_consultorio',
       'mesa_universal_para_exploracion_consultorio', 'otoscopio_consultorio',
       'oximetro_de_pulso_consultorio',
       'paquetes_refrigerantes_para_termo_consultorio',
       'porta_cubeta_rodable_con_protector_de_hule_consultorio',
       'porta_rollo_para_papel_kraft_o_sabanas_consultorio',
       'silla_para_el_acompanante_consultorio',
       'silla_para_el_paciente_consultorio',
       'sillon_giratorio_de_respaldo_bajo_consultorio',
       'termo_congelante_integrado_para_transporte_y_conservacion_de_vacunas_consultorio',
       'termometro_de_vastago_consultorio', 'termometro_digital_consultorio',
       'tijera_recta_consultorio',
       'torundera_con_tapa_de_acero_inoxidable_consultorio',
       'turno_consultorio', 'vaso_contenedor__de_vacunas_consultorio',
       'latitud', 'longitud'],
      dtype='object')

In [493]:
columnas_preguntas = resultado.columns.difference([
    "entidad",
    "clues_imb",
    "nombre_de_la_unidad",
    "internet",
    "consultorios_habilitados",
    "consultorio",
    "turno_consultorio",
    "latitud",
    "longitud",
])

resultado[columnas_preguntas] = (
    resultado[columnas_preguntas]
    .apply(pd.to_numeric, errors="coerce")

    .fillna(0))

In [494]:
# Columnas que son preguntas
columnas_preguntas = resultado.columns.difference([
    "entidad",
    "clues_imb",
    "nombre_de_la_unidad",
    "internet",
    "consultorios_habilitados",
    "consultorio",
    "latitud",
    "longitud",
])

resumen = (
    resultado
    .groupby("clues_imb", as_index=False)
    .agg(
        entidad=("entidad", "first"),
        nombre_de_la_unidad=("nombre_de_la_unidad", "first"),
        internet=("internet", "first"),
        consultorios_habilitados=("consultorios_habilitados", "max"),
        consultorio=("consultorio", "max"),   # Número de consultorios
        **{col: (col, "sum") for col in columnas_preguntas}

    ))

In [495]:
resumen = resumen.merge(
    clues[["entidad", "clues_imb", "latitud", "longitud"]],
    on=["entidad", "clues_imb"],
    how="left"
)

In [496]:
resumen

,clues_imb,entidad,nombre_de_la_unidad,internet,consultorios_habilitados,consultorio,banco_de_altura_consultorio,banco_giratorio_consultorio,bascula_electronica__con_estadimetro_consultorio,bascula_pesabebes_electronica_consultorio,...,sillon_giratorio_de_respaldo_bajo_consultorio,termo_congelante_integrado_para_transporte_y_conservacion_de_vacunas_consultorio,termometro_de_vastago_consultorio,termometro_digital_consultorio,tijera_recta_consultorio,torundera_con_tapa_de_acero_inoxidable_consultorio,turno_consultorio,vaso_contenedor__de_vacunas_consultorio,latitud,longitud
0,BCIMB000302,BAJA CALIFORNIA,HÉROES DE LA INDEPENDENCIA,True,1.0,1.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,1.0,Matutino,0.0,31.610915,-115.890043
1,BCIMB000314,BAJA CALIFORNIA,VALLE DE LA TRINIDAD,True,2.0,1.0,1.0,1.0,1.0,1.0,...,1.0,0.0,0.0,0.0,0.0,1.0,Matutino,0.0,31.402612,-115.737995
2,BCIMB000536,BAJA CALIFORNIA,DURANGO,True,1.0,1.0,1.0,1.0,1.0,0.0,...,0.0,1.0,1.0,1.0,1.0,1.0,Matutino,1.0,32.249817,-115.256147
3,BCIMB000990,BAJA CALIFORNIA,PEDREGAL DE SANTA JULIA,True,NaN,1.0,2.0,0.0,1.0,2.0,...,2.0,4.0,5.0,0.0,1.0,0.0,Matutino,2.0,32.487771,-117.059844
4,CCIMB000184,CAMPECHE,CENTRO DE SALUD PUERTO RICO,True,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,1.0,1.0,1.0,Vespertino,0.0,18.620689,-91.939520
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
788,ZSIMB001641,ZACATECAS,CENTRO DE SALUD ZACATECAS,None,12.0,6.0,6.0,5.0,6.0,3.0,...,6.0,0.0,0.0,6.0,0.0,6.0,VespertinoVespertinoAmbosAmbos,0.0,22.773375,-102.597295
789,ZSIMB001822,ZACATECAS,CENTRO DE SALUD COL. EMILIANO ZAPATA,True,2.0,1.0,1.0,1.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,Vespertino,0.0,23.191013,-102.866952
790,ZSIMB002102,ZACATECAS,CENTRO DE SALUD MARTÍNEZ DOMÍNGUEZ,True,2.0,1.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,Vespertino,0.0,22.749695,-102.478009
791,ZSIMB002435,ZACATECAS,CENTRO DE SALUD LA PINTA,True,2.0,2.0,2.0,2.0,0.0,0.0,...,2.0,0.0,0.0,0.0,0.0,2.0,VespertinoVespertino,0.0,22.785735,-102.565062
792,ZSIMB002522,ZACATECAS,CENTRO DE SALUD FRESNILLO 2,True,6.0,4.0,4.0,4.0,4.0,4.0,...,4.0,0.0,0.0,4.0,0.0,4.0,VespertinoVespertinoVespertinoVespertino,0.0,23.183786,-102.864666

In [497]:
# resultado.loc[
#     resultado["clues_imb"] == "CCIMB000954",
#     [
#         "consultorio",
#        'turno_consultorio'
#     ]
# ]

In [ ]:
# resultado.loc[
#     resultado["clues_imb"] == "CCIMB000930",
#     "banco_de_altura_consultorio"
# ].apply(type)

Series([], Name: banco_de_altura_consultorio, dtype: float64)

In [ ]:
# Normalizar internet a 0/1 sin warnings de replace
resumen["internet"] = (
    resumen["internet"]
    .astype(str)
    .str.strip()
    .str.lower()
    .map({
        "true": 1,
        "false": 0,
        "1": 1,
        "0": 0,
        "si": 1,
        "no": 0,
    })
    .fillna(0)
    .astype(int)
)

# Columnas que NO se deben sumar
columnas_excluir = [
    "entidad",
    "clues_imb",
    "nombre_de_la_unidad",
    "turno_consultorio",
]

# Seleccionar columnas a sumar y forzarlas a numerico
columnas_sumar = [c for c in resumen.columns if c not in columnas_excluir]
resumen[columnas_sumar] = (
    resumen[columnas_sumar]
    .apply(pd.to_numeric, errors="coerce")
    .fillna(0)
)

# Agrupar por entidad
resumen_entidad = (
    resumen
    .groupby("entidad", as_index=False)[columnas_sumar]
    .sum()
)

# # Mostrar resultado
# print(resumen_entidad.head())

           entidad  internet  consultorios_habilitados  consultorio  \
0  BAJA CALIFORNIA         4                       4.0          4.0
1         CAMPECHE         5                       7.0          5.0
2          CHIAPAS        13                      47.0         33.0
3           COLIMA        15                       9.0         17.0
4         GUERRERO       210                     278.0        343.0

   banco_de_altura_consultorio  banco_giratorio_consultorio  \
0                          4.0                          3.0
1                          4.0                          5.0
2                         49.0                         48.0
3                         17.0                         15.0
4                        354.0                        300.0

   bascula_electronica__con_estadimetro_consultorio  \
0                                               3.0
1                                               1.0
2                                              35.0
3                                              15.0
4                                             172.0

   bascula_pesabebes_electronica_consultorio  \
0                                        3.0
1                                        1.0
2                                       23.0
3                                       14.0
4                                      247.0

   bote_sanitario_con_pedal_consultorio  \
0                                   8.0
1                                   5.0
2                                  17.0
3                                   8.0
4                                 161.0

   caja_portalaminilla_de_plastico_con_separadores_consultorio  ...  \
0                                                1.0            ...
1                                                0.0            ...
2                                               14.0            ...
3                                                5.0            ...
4                                               76.0            ...

   silla_para_el_paciente_consultorio  \
0                                 5.0
1                                 5.0
2                                66.0
3                                16.0
4                               577.0

   sillon_giratorio_de_respaldo_bajo_consultorio  \
0                                            4.0
1                                            2.0
2                                           84.0
3                                            5.0
4                                          289.0

   termo_congelante_integrado_para_transporte_y_conservacion_de_vacunas_consultorio  \
0                                                5.0
1                                                3.0
2                                               75.0
3                                               19.0
4                                              432.0

   termometro_de_vastago_consultorio  termometro_digital_consultorio  \
0                                6.0                             1.0
1                                2.0                             4.0
2                               43.0                            50.0
3                               16.0                            17.0
4                              285.0                           315.0

   tijera_recta_consultorio  \
0                       3.0
1                       2.0
2                      20.0
3                      16.0
4                     286.0

   torundera_con_tapa_de_acero_inoxidable_consultorio  \
0                                                3.0
1                                                4.0
2                                               48.0
3                                               17.0
4                                              410.0

   vaso_contenedor__de_vacunas_consultorio      latitud      longitud
0                                      3.0   127.751115   -463.944029
1                                      1.0    94.054404   -457.314350
2                                     30.0   292.471834  -1665.460187
3                                     11.0   288.736800  -1555.835000
4                                    320.0  5087.000543 -28762.436742

[5 rows x 50 columns]

In [500]:
# Convertir internet a 0/1
resumen["internet"] = (
    resumen["internet"]
    .replace({
        True: 1,
        False: 0,
        "True": 1,
        "False": 0
    })
    .fillna(0)
    .astype(int)
)

# Columnas que NO se deben sumar
columnas_excluir = [
    "entidad",
    "clues_imb",
    "nombre_de_la_unidad",
    "turno_consultorio",
]

# Columnas a sumar
columnas_sumar = resumen.columns.difference(columnas_excluir)

# Agrupar por entidad
resumen_entidad = (
    resumen
    .groupby("entidad", as_index=False)[columnas_sumar]
    .sum()
)

In [501]:
resumen_entidad

,entidad,banco_de_altura_consultorio,banco_giratorio_consultorio,bascula_electronica__con_estadimetro_consultorio,bascula_pesabebes_electronica_consultorio,bote_sanitario_con_pedal_consultorio,caja_portalaminilla_de_plastico_con_separadores_consultorio,carta_snellen_con_marco_consultorio,charola_de_mayo_de_acero_inoxidable_consultorio,cinta_metrica_consultorio,...,porta_rollo_para_papel_kraft_o_sabanas_consultorio,silla_para_el_acompanante_consultorio,silla_para_el_paciente_consultorio,sillon_giratorio_de_respaldo_bajo_consultorio,termo_congelante_integrado_para_transporte_y_conservacion_de_vacunas_consultorio,termometro_de_vastago_consultorio,termometro_digital_consultorio,tijera_recta_consultorio,torundera_con_tapa_de_acero_inoxidable_consultorio,vaso_contenedor__de_vacunas_consultorio
0,BAJA CALIFORNIA,4.0,3.0,3.0,3.0,8.0,1.0,2.0,4.0,6.0,...,3.0,5.0,5.0,4.0,5.0,6.0,1.0,3.0,3.0,3.0
1,CAMPECHE,4.0,5.0,1.0,1.0,5.0,0.0,2.0,5.0,4.0,...,0.0,4.0,5.0,2.0,3.0,2.0,4.0,2.0,4.0,1.0
2,CHIAPAS,49.0,48.0,35.0,23.0,17.0,14.0,14.0,42.0,73.0,...,20.0,57.0,66.0,84.0,75.0,43.0,50.0,20.0,48.0,30.0
3,COLIMA,17.0,15.0,15.0,14.0,8.0,5.0,9.0,16.0,16.0,...,7.0,17.0,16.0,5.0,19.0,16.0,17.0,16.0,17.0,11.0
4,GUERRERO,354.0,300.0,172.0,247.0,161.0,76.0,65.0,300.0,371.0,...,92.0,464.0,577.0,289.0,432.0,285.0,315.0,286.0,410.0,320.0
5,HIDALGO,2.0,1.0,0.0,2.0,2.0,1.0,0.0,0.0,3.0,...,0.0,2.0,2.0,1.0,4.0,3.0,4.0,2.0,2.0,2.0
6,MEXICO,292.0,251.0,82.0,122.0,196.0,19.0,30.0,115.0,201.0,...,103.0,366.0,395.0,205.0,173.0,232.0,140.0,70.0,164.0,284.0
7,MICHOACAN DE OCAMPO,20.0,9.0,2.0,1.0,2.0,2.0,8.0,7.0,16.0,...,0.0,26.0,24.0,20.0,8.0,6.0,5.0,9.0,7.0,5.0
8,MORELOS,23.0,12.0,6.0,0.0,12.0,0.0,5.0,9.0,23.0,...,1.0,22.0,22.0,10.0,1.0,1.0,9.0,4.0,7.0,1.0
9,NAYARIT,38.0,40.0,13.0,21.0,15.0,8.0,10.0,28.0,41.0,...,11.0,56.0,68.0,35.0,56.0,34.0,38.0,32.0,49.0,34.0
10,OAXACA,30.0,25.0,9.0,6.0,23.0,4.0,9.0,23.0,38.0,...,5.0,47.0,56.0,28.0,14.0,12.0,21.0,20.0,34.0,10.0
11,QUINTANA ROO,118.0,97.0,60.0,67.0,35.0,11.0,15.0,83.0,118.0,...,45.0,151.0,224.0,88.0,93.0,62.0,114.0,73.0,137.0,66.0
12,SAN LUIS POTOSI,38.0,35.0,15.0,12.0,32.0,1.0,4.0,29.0,26.0,...,11.0,36.0,42.0,36.0,13.0,12.0,23.0,25.0,30.0,14.0
13,SINALOA,11.0,17.0,2.0,1.0,9.0,0.0,0.0,4.0,11.0,...,0.0,12.0,12.0,11.0,0.0,0.0,9.0,2.0,8.0,0.0
14,TABASCO,14.0,14.0,7.0,10.0,13.0,9.0,6.0,13.0,21.0,...,2.0,19.0,22.0,17.0,23.0,14.0,13.0,13.0,20.0,14.0
15,TAMAULIPAS,97.0,76.0,23.0,30.0,50.0,12.0,24.0,79.0,88.0,...,22.0,113.0,130.0,60.0,200.0,91.0,73.0,77.0,91.0,74.0
16,VERACRUZ DE IGNACIO DE LA LLAVE,64.0,59.0,25.0,12.0,45.0,21.0,6.0,44.0,82.0,...,42.0,112.0,123.0,71.0,44.0,56.0,50.0,37.0,39.0,32.0
17,ZACATECAS,34.0,22.0,18.0,9.0,30.0,1.0,12.0,23.0,35.0,...,75.0,37.0,37.0,37.0,0.0,0.0,19.0,5.0,19.0,0.0

In [502]:
import json
from pathlib import Path
from datetime import datetime

base_clues = (
    base[["clues_imb"]]
    .dropna()
    .drop_duplicates()
    .assign(clues_imb=lambda df: df["clues_imb"].astype(str).str.strip())
)
base_clues = base_clues[base_clues["clues_imb"] != ""]

output_dir = Path.cwd() / "public"
output_dir.mkdir(parents=True, exist_ok=True)

clues_path = output_dir / "base_clues.json"
clues_path.write_text(
    json.dumps(base_clues.to_dict(orient="records"), ensure_ascii=False, indent=2),
    encoding="utf-8",
)

base_clues_total = (
    base["clues_imb"]
    .dropna()
    .astype(str)
    .str.strip()
)
base_clues_total = base_clues_total[base_clues_total != ""]

base_entidades_esperadas = (
    base["entidad"]
    .dropna()
    .astype(str)
    .str.strip()
)
base_entidades_esperadas = base_entidades_esperadas[base_entidades_esperadas != ""].nunique()

meta_payload = {
    "clues_total": int(len(base_clues_total)),
    "clues_unicas": int(base_clues["clues_imb"].nunique()),
    "entidades_esperadas": int(base_entidades_esperadas),
    "script_last_run_at": datetime.now().isoformat(timespec="seconds"),
}

meta_path = output_dir / "base_meta.json"
meta_path.write_text(
    json.dumps(meta_payload, ensure_ascii=False, indent=2),
    encoding="utf-8",
)

print(f"Archivo generado: {clues_path}")
print(f"Archivo generado: {meta_path}")
print(f"CLUES total base: {meta_payload['clues_total']}")
print(f"CLUES unicas base: {meta_payload['clues_unicas']}")
print(f"Entidades esperadas: {meta_payload['entidades_esperadas']}")
print(f"Script run at: {meta_payload['script_last_run_at']}")

Archivo generado: c:\Users\jose.valdez\Downloads\repor-arm\reporte-_angeles\public\base_clues.json
Archivo generado: c:\Users\jose.valdez\Downloads\repor-arm\reporte-_angeles\public\base_meta.json
CLUES total base: 2827
CLUES unicas base: 2191
Entidades esperadas: 22
Script run at: 2026-07-23T11:55:07

In [503]:
# Exportar CLUES filtradas (>=90%) a public/tabla_unidades.json
tabla_unidades_path = output_dir / "tabla_unidades.json"
clues_para_export = (
    tabla_unidades["clues"]
    .dropna()
    .astype(str)
    .str.strip()
    .unique()
    .tolist()
)
tabla_unidades_path.write_text(
    json.dumps(clues_para_export, ensure_ascii=False, indent=2),
    encoding="utf-8",
)
print(f"Archivo generado: {tabla_unidades_path}")
print(f"CLUES exportadas (>=90%): {len(clues_para_export)}")

Archivo generado: c:\Users\jose.valdez\Downloads\repor-arm\reporte-_angeles\public\tabla_unidades.json
CLUES exportadas (>=90%): 793

In [504]:
# Exportar puntos geo de CLUES a public/clues_geo.json
geo_cols = ["clues_imb", "nombre_de_la_unidad", "entidad", "latitud", "longitud", "internet", "consultorio"]
available_cols = [c for c in geo_cols if c in resumen.columns]

clues_geo = (
    resumen[available_cols]
    .dropna(subset=["latitud", "longitud"])
    .copy()
)

clues_geo["internet"] = clues_geo["internet"].apply(
    lambda v: str(v).strip().lower() in ("true", "1", "si", "sí", "yes")
)
clues_geo["latitud"] = pd.to_numeric(clues_geo["latitud"], errors="coerce")
clues_geo["longitud"] = pd.to_numeric(clues_geo["longitud"], errors="coerce")
clues_geo = clues_geo.dropna(subset=["latitud", "longitud"])

# Agregar % llenado desde tabla_unidades
tabla_pct = tabla_unidades[["clues", "porcentaje"]].rename(
    columns={"clues": "clues_imb", "porcentaje": "pct_llenado"}
)
clues_geo = clues_geo.merge(tabla_pct, on="clues_imb", how="left")
clues_geo["pct_llenado"] = clues_geo["pct_llenado"].fillna(0).round(1)

clues_geo_path = output_dir / "clues_geo.json"
clues_geo_path.write_text(
    json.dumps(
        clues_geo.rename(columns={"latitud": "lat", "longitud": "lng", "consultorio": "consultorios"})
                 .to_dict(orient="records"),
        ensure_ascii=False,
        indent=2
    ),
    encoding="utf-8",
)
print(f"Archivo generado: {clues_geo_path}")
print(f"Puntos geo exportados: {len(clues_geo)}")

Archivo generado: c:\Users\jose.valdez\Downloads\repor-arm\reporte-_angeles\public\clues_geo.json
Puntos geo exportados: 793

In [505]:
import numpy as np

def _clean_json(df):
    """Convierte NaN/Inf a None para que sea JSON serializable."""
    return df.replace({np.nan: None, np.inf: None, -np.inf: None}).to_dict(orient="records")

# resumen (una fila por CLUES)
resumen_path = output_dir / "resumen.json"
resumen_path.write_text(
    json.dumps(_clean_json(resumen), ensure_ascii=False, indent=2),
    encoding="utf-8",
)
print(f"Archivo generado: {resumen_path}  ({len(resumen)} filas)")

# resultado (una fila por consultorio)
resultado_path = output_dir / "resultado.json"
resultado_path.write_text(
    json.dumps(_clean_json(resultado), ensure_ascii=False, indent=2),
    encoding="utf-8",
)
print(f"Archivo generado: {resultado_path}  ({len(resultado)} filas)")

# resumen_entidad (una fila por estado)
resumen_entidad_path = output_dir / "resumen_entidad.json"
resumen_entidad_path.write_text(
    json.dumps(_clean_json(resumen_entidad), ensure_ascii=False, indent=2),
    encoding="utf-8",
)
print(f"Archivo generado: {resumen_entidad_path}  ({len(resumen_entidad)} filas)")

Archivo generado: c:\Users\jose.valdez\Downloads\repor-arm\reporte-_angeles\public\resumen.json  (793 filas)
Archivo generado: c:\Users\jose.valdez\Downloads\repor-arm\reporte-_angeles\public\resultado.json  (1162 filas)
Archivo generado: c:\Users\jose.valdez\Downloads\repor-arm\reporte-_angeles\public\resumen_entidad.json  (18 filas)

In [506]:
base_clues_total = (
    base["clues_imb"]
    .dropna()
    .astype(str)
    .str.strip()
)
base_clues_total = base_clues_total[base_clues_total != ""]

base_clues_unicas = base_clues_total.nunique()
base_clues_filas = len(base_clues_total)
base_entidades_esperadas = (
    base["entidad"]
    .dropna()
    .astype(str)
    .str.strip()
)
base_entidades_esperadas = base_entidades_esperadas[base_entidades_esperadas != ""].nunique()

print("clues filas base:", base_clues_filas)
print("clues unicas base:", base_clues_unicas)
print("entidades esperadas base:", base_entidades_esperadas)

clues filas base: 2827
clues unicas base: 2191
entidades esperadas base: 22

## faltantes

In [507]:
# TABLA - COMPLETITUD POR UNIDAD (todas las CLUES, sin filtrar)
# Renombrada a tu_faltantes para no sobreescribir tabla_unidades

n_preguntas = len(b)

consultorios = (
    base_an
    .groupby(["clues_imb","entidad",'nombre_de_la_unidad'],as_index=False)
    ["consultorio"]
    .max()
)
consultorios.rename(columns={"consultorio":"consultorios"}, inplace=True)

respondidas = (
    base_an
    .groupby(["clues_imb","entidad",'nombre_de_la_unidad'])
    .size()
    .reset_index(name="respondidas")
)

tu_faltantes = consultorios.merge(
    respondidas,
    on=["clues_imb","entidad",'nombre_de_la_unidad']
)

tu_faltantes["esperadas"] = tu_faltantes["consultorios"] * n_preguntas

tu_faltantes["porcentaje"] = (
    tu_faltantes["respondidas"] / tu_faltantes["esperadas"] * 100
).round(1).clip(upper=100)

tu_faltantes = (
    tu_faltantes
    .rename(columns={"clues_imb":"clues"})
    .sort_values("porcentaje")
)

In [508]:
# TABLA BASE por unidad (para la sección de faltantes)
# Renombrada a tu_base para no sobreescribir tabla_unidades

n_preguntas = len(b)

consultorios = (
    base_an
    .groupby(["clues_imb", "entidad", "nombre_de_la_unidad"], as_index=False)
    ["consultorio"]
    .max()
)
consultorios.rename(columns={"consultorio": "consultorios"}, inplace=True)

respondidas = (
    base_an
    .groupby(["clues_imb", "entidad", "nombre_de_la_unidad"])
    .size()
    .reset_index(name="respondidas")
)

tu_base = consultorios.merge(
    respondidas,
    on=["clues_imb", "entidad", "nombre_de_la_unidad"],
    how="left"
)

In [509]:
# ============================================
# TABLA 3 - PIVOT POR CONSULTORIO (SIN SUFIJOS)

# ============================================

# Solo respuestas del formulario
respuesta = base_an[base_an["tipo_registro"] == "respuesta"].copy()

# Limpieza de campos clave
respuesta["pregunta"] = respuesta["pregunta"].astype(str).str.strip()
respuesta["consultorio"] = pd.to_numeric(respuesta["consultorio"], errors="coerce")
respuesta = respuesta.dropna(subset=["pregunta", "consultorio"])
respuesta["consultorio"] = respuesta["consultorio"].astype(int)

# Elimina sufijos por consultorio (_1, _2, _3, ...)
respuesta["pregunta_base"] = respuesta["pregunta"].str.replace(r"_\d+$", "", regex=True)

# Pivot por unidad + consultorio usando solo pregunta base
pivot_consultorio = respuesta.pivot_table(
    index=["entidad", "clues_imb", "nombre_de_la_unidad", "consultorio"],
    columns="pregunta_base",
    values="valor",
    aggfunc="first"
).reset_index()

# Vista rápida
pivot_consultorio.head()

pregunta_base,entidad,clues_imb,nombre_de_la_unidad,consultorio,banco_de_altura_consultorio,banco_giratorio_consultorio,bascula_electronica__con_estadimetro_consultorio,bascula_pesabebes_electronica_consultorio,bote_sanitario_con_pedal_consultorio,caja_portalaminilla_de_plastico_con_separadores_consultorio,...,silla_para_el_acompanante_consultorio,silla_para_el_paciente_consultorio,sillon_giratorio_de_respaldo_bajo_consultorio,termo_congelante_integrado_para_transporte_y_conservacion_de_vacunas_consultorio,termometro_de_vastago_consultorio,termometro_digital_consultorio,tijera_recta_consultorio,torundera_con_tapa_de_acero_inoxidable_consultorio,turno_consultorio,vaso_contenedor__de_vacunas_consultorio
0,BAJA CALIFORNIA,BCIMB000092,FRACCIONAMIENTO MAR,1,1,0,0,0,0,0,...,1,1,1,NaN,NaN,NaN,NaN,NaN,Matutino,NaN
1,BAJA CALIFORNIA,BCIMB000092,FRACCIONAMIENTO MAR,2,1,1,1,0,1,0,...,1,1,1,NaN,NaN,NaN,NaN,NaN,Matutino,NaN
2,BAJA CALIFORNIA,BCIMB000092,FRACCIONAMIENTO MAR,3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Matutino,NaN
3,BAJA CALIFORNIA,BCIMB000302,HÉROES DE LA INDEPENDENCIA,1,0,1,0,0,0,0,...,1,1,1,0,0,0,1,1,Matutino,0
4,BAJA CALIFORNIA,BCIMB000314,VALLE DE LA TRINIDAD,1,1,1,1,1,1,0,...,1,1,1,0,0,0,0,1,Matutino,0

In [510]:
# Conteo de preguntas unicas pivoteadas
n_preguntas_pivoteadas = respuesta["pregunta_base"].nunique()
print("Preguntas unicas pivoteadas:", n_preguntas_pivoteadas)

# Validacion contra columnas del pivot (excluyendo llaves del indice)
llaves = ["entidad", "clues_imb", "nombre_de_la_unidad", "consultorio"]
print("Columnas de preguntas en pivot:", len([c for c in pivot_consultorio.columns if c not in llaves]))

Preguntas unicas pivoteadas: 45
Columnas de preguntas en pivot: 45

In [511]:
# ============================================
# TABLA 4 - LLENADO POR CLUES Y CONSULTORIO
# Base esperada: preguntas de b (excluyendo 'turno' y filas 0,1,2,5)
# ============================================

import re
import unicodedata


def normalizar_pregunta(x: str) -> str:
    s = str(x).strip().lower()
    s = unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode("ascii")
    s = re.sub(r"_\d+$", "", s)                # quita sufijo numerico
    s = re.sub(r"[^a-z0-9]+", "_", s)           # espacios/simbolos -> _
    s = re.sub(r"_+", "_", s).strip("_")       # limpia _ repetidos
    s = re.sub(r"_consultorio$", "", s)         # quita sufijo fijo consultorio
    return s

# 1) Catalogo esperado desde b (quitando filas especificas)
b_filtrado = b.drop(index=[0, 1, 2, 5], errors="ignore").copy()

catalogo_b = b_filtrado["preguntas"].dropna().astype(str).str.strip()
catalogo_b = catalogo_b[catalogo_b != ""]
catalogo_b_norm = catalogo_b.map(normalizar_pregunta)
catalogo_b_norm = catalogo_b_norm[catalogo_b_norm.str.contains("turno") == False]
set_catalogo_b = set(catalogo_b_norm.tolist())
n_preguntas_esperadas = len(set_catalogo_b)

print(f"Preguntas esperadas desde b filtrado (sin turno): {n_preguntas_esperadas}")

# 2) Respuestas del formulario por consultorio
resp = base_an[base_an["tipo_registro"] == "respuesta"].copy()
resp["pregunta"] = resp["pregunta"].astype(str).str.strip()
resp["pregunta_norm"] = resp["pregunta"].map(normalizar_pregunta)
resp["consultorio"] = pd.to_numeric(resp["consultorio"], errors="coerce")
resp = resp.dropna(subset=["clues_imb", "consultorio", "pregunta_norm"])
resp = resp[resp["pregunta_norm"] != ""]
resp = resp[resp["pregunta_norm"].str.contains("turno") == False]
resp["consultorio"] = resp["consultorio"].astype(int)

keys = ["entidad", "clues_imb", "nombre_de_la_unidad", "consultorio"]

# 3) Calcula por consultorio: respondidas, faltantes, extras y porcentaje
filas = []
faltantes_detalle = []

for k, grp in resp.groupby(keys, dropna=False):
    preguntas_unicas = set(grp["pregunta_norm"].dropna().astype(str).str.strip())
    preguntas_unicas.discard("")

    respondidas_validas = len(preguntas_unicas & set_catalogo_b)
    faltantes_set = set_catalogo_b - preguntas_unicas
    extras_set = preguntas_unicas - set_catalogo_b

    faltantes = sorted(faltantes_set)
    extras = sorted(extras_set)

    porcentaje = round((respondidas_validas / n_preguntas_esperadas) * 100, 1) if n_preguntas_esperadas else 0.0

    filas.append({
        "entidad": k[0],
        "clues_imb": k[1],
        "nombre_de_la_unidad": k[2],
        "consultorio": k[3],
        "preguntas_esperadas": n_preguntas_esperadas,
        "preguntas_respondidas_validas": respondidas_validas,
        "faltantes": len(faltantes),
        "extras_fuera_catalogo": len(extras),
        "porcentaje_llenado": porcentaje,
        "lista_faltantes": ", ".join(faltantes),
        "lista_extras": ", ".join(extras),
    })

    for pregunta_faltante in faltantes:
        faltantes_detalle.append({
            "entidad": k[0],
            "clues_imb": k[1],
            "nombre_de_la_unidad": k[2],
            "consultorio": k[3],
            "pregunta_faltante": pregunta_faltante,
        })

tabla_llenado_consultorio = pd.DataFrame(filas).sort_values(
    ["clues_imb", "consultorio"],
    ascending=[True, True]
).reset_index(drop=True)

# 4) Detalle de faltantes por consultorio
faltantes_por_consultorio = pd.DataFrame(faltantes_detalle).sort_values(
    ["clues_imb", "consultorio", "pregunta_faltante"],
    ascending=[True, True, True]
).reset_index(drop=True)

# 5) Resumen por CLUES (acumulado de consultorios)
resumen_llenado_clues = (
    tabla_llenado_consultorio
    .groupby(["entidad", "clues_imb", "nombre_de_la_unidad"], as_index=False)
    .agg(
        consultorios_reportados=("consultorio", "nunique"),
        preguntas_esperadas_por_consultorio=("preguntas_esperadas", "max"),
        preguntas_respondidas_validas_total=("preguntas_respondidas_validas", "sum"),
        faltantes_total=("faltantes", "sum"),
        extras_fuera_catalogo_total=("extras_fuera_catalogo", "sum"),
    )
)

resumen_llenado_clues["preguntas_esperadas_total"] = (
    resumen_llenado_clues["consultorios_reportados"]
    * resumen_llenado_clues["preguntas_esperadas_por_consultorio"]
)

resumen_llenado_clues["porcentaje_llenado_total"] = (
    resumen_llenado_clues["preguntas_respondidas_validas_total"]
    / resumen_llenado_clues["preguntas_esperadas_total"]
    * 100
).round(1)

print("\nVista por consultorio (primeras filas):")
display(tabla_llenado_consultorio.head())

print("\nDetalle de faltantes con consultorio (primeras filas):")
display(faltantes_por_consultorio.head())

Preguntas esperadas desde b filtrado (sin turno): 44

Vista por consultorio (primeras filas):

,entidad,clues_imb,nombre_de_la_unidad,consultorio,preguntas_esperadas,preguntas_respondidas_validas,faltantes,extras_fuera_catalogo,porcentaje_llenado,lista_faltantes,lista_extras
0,BAJA CALIFORNIA,BCIMB000092,FRACCIONAMIENTO MAR,1,44,30,14,0,68.2,"cinta_metrica, estetoscopio_capsula_doble, mar...",
1,BAJA CALIFORNIA,BCIMB000092,FRACCIONAMIENTO MAR,2,44,30,14,0,68.2,"estadimetro_pediatrico, estetoscopio_capsula_d...",
2,BAJA CALIFORNIA,BCIMB000302,HÉROES DE LA INDEPENDENCIA,1,44,44,0,0,100.0,,
3,BAJA CALIFORNIA,BCIMB000314,VALLE DE LA TRINIDAD,1,44,44,0,0,100.0,,
4,BAJA CALIFORNIA,BCIMB000536,DURANGO,1,44,44,0,0,100.0,,

Detalle de faltantes con consultorio (primeras filas):

,entidad,clues_imb,nombre_de_la_unidad,consultorio,pregunta_faltante
0,BAJA CALIFORNIA,BCIMB000092,FRACCIONAMIENTO MAR,1,cinta_metrica
1,BAJA CALIFORNIA,BCIMB000092,FRACCIONAMIENTO MAR,1,estetoscopio_capsula_doble
2,BAJA CALIFORNIA,BCIMB000092,FRACCIONAMIENTO MAR,1,martillo_percusor
3,BAJA CALIFORNIA,BCIMB000092,FRACCIONAMIENTO MAR,1,mesa_de_mayo_de_acero_inoxidable
4,BAJA CALIFORNIA,BCIMB000092,FRACCIONAMIENTO MAR,1,mesa_pasteur

In [512]:
# Consultorios con >= 90% de llenado
tabla_llenado_90 = tabla_llenado_consultorio[
    tabla_llenado_consultorio["porcentaje_llenado"] >= 90
].reset_index(drop=True)

print(f"Consultorios con >= 90% de llenado: {len(tabla_llenado_90)}")

# Faltantes solo de esos consultorios
clues_cons_90 = tabla_llenado_90[["clues_imb", "consultorio"]]

faltantes_90 = faltantes_por_consultorio.merge(
    clues_cons_90,
    on=["clues_imb", "consultorio"],
    how="inner"
).reset_index(drop=True)

print(f"Registros de faltantes en consultorios >= 90%: {len(faltantes_90)}")

display(tabla_llenado_90)
display(faltantes_90)

Consultorios con >= 90% de llenado: 1314
Registros de faltantes en consultorios >= 90%: 733

,entidad,clues_imb,nombre_de_la_unidad,consultorio,preguntas_esperadas,preguntas_respondidas_validas,faltantes,extras_fuera_catalogo,porcentaje_llenado,lista_faltantes,lista_extras
0,BAJA CALIFORNIA,BCIMB000302,HÉROES DE LA INDEPENDENCIA,1,44,44,0,0,100.0,,
1,BAJA CALIFORNIA,BCIMB000314,VALLE DE LA TRINIDAD,1,44,44,0,0,100.0,,
2,BAJA CALIFORNIA,BCIMB000536,DURANGO,1,44,44,0,0,100.0,,
3,BAJA CALIFORNIA,BCIMB000990,PEDREGAL DE SANTA JULIA,1,44,44,0,0,100.0,,
4,CAMPECHE,CCIMB000184,CENTRO DE SALUD PUERTO RICO,1,44,44,0,0,100.0,,
...,...,...,...,...,...,...,...,...,...,...,...
1309,ZACATECAS,ZSIMB002435,CENTRO DE SALUD LA PINTA,2,44,44,0,0,100.0,,
1310,ZACATECAS,ZSIMB002522,CENTRO DE SALUD FRESNILLO 2,1,44,44,0,0,100.0,,
1311,ZACATECAS,ZSIMB002522,CENTRO DE SALUD FRESNILLO 2,2,44,44,0,0,100.0,,
1312,ZACATECAS,ZSIMB002522,CENTRO DE SALUD FRESNILLO 2,3,44,44,0,0,100.0,,
1313,ZACATECAS,ZSIMB002522,CENTRO DE SALUD FRESNILLO 2,4,44,44,0,0,100.0,,

,entidad,clues_imb,nombre_de_la_unidad,consultorio,pregunta_faltante
0,CAMPECHE,CCIMB000225,CENTRO DE SALUD ISLA AGUADA,1,banco_de_altura
1,CAMPECHE,CCIMB000225,CENTRO DE SALUD ISLA AGUADA,1,espejo_vestidor
2,CAMPECHE,CCIMB000225,CENTRO DE SALUD ISLA AGUADA,1,estetoscopio_pinard_o_doppler_fetal_portatil
3,CAMPECHE,CCIMB000225,CENTRO DE SALUD ISLA AGUADA,1,lavabo
4,CAMPECHE,CCIMB000230,CENTRO DE SALUD EMILIANO ZAPATA,1,termometro_digital
...,...,...,...,...,...
728,ZACATECAS,ZSIMB000434,CENTRO DE SALUD COL. TIERRA Y LIBERTAD,1,estetoscopio_pinard_o_doppler_fetal_portatil
729,ZACATECAS,ZSIMB001402,CENTRO DE SALUD SANTA LUCÍA DE LA SIERRA,1,banco_giratorio
730,ZACATECAS,ZSIMB001641,CENTRO DE SALUD ZACATECAS,2,estadimetro_pediatrico
731,ZACATECAS,ZSIMB001641,CENTRO DE SALUD ZACATECAS,4,banco_giratorio
732,ZACATECAS,ZSIMB001641,CENTRO DE SALUD ZACATECAS,6,espejo_vestidor

In [513]:
from pathlib import Path
from datetime import date

ruta = Path(fr"C:\Users\{usuario}\Downloads\faltantes_90_{date.today()}.xlsx")
faltantes_90.to_excel(ruta, index=False)
print(f"Archivo guardado en: {ruta}")

Archivo guardado en: C:\Users\jose.valdez\Downloads\faltantes_90_2026-07-23.xlsx

In [514]:
faltantes_90_agrupado = (
    faltantes_90
    .groupby(["entidad", "clues_imb", "nombre_de_la_unidad", "consultorio"], as_index=False)
    .agg(
        n_faltantes=("pregunta_faltante", "count"),
        preguntas_faltantes=("pregunta_faltante", lambda x: ", ".join(sorted(x))),
    )
    .sort_values(["clues_imb", "consultorio"])
    .reset_index(drop=True)
)

print(f"Filas agrupadas: {len(faltantes_90_agrupado)}")
faltantes_90_agrupado

Filas agrupadas: 355

,entidad,clues_imb,nombre_de_la_unidad,consultorio,n_faltantes,preguntas_faltantes
0,CAMPECHE,CCIMB000225,CENTRO DE SALUD ISLA AGUADA,1,4,"banco_de_altura, espejo_vestidor, estetoscopio..."
1,CAMPECHE,CCIMB000230,CENTRO DE SALUD EMILIANO ZAPATA,1,1,termometro_digital
2,CAMPECHE,CCIMB000394,CENTRO DE SALUD 5 DE FEBRERO,1,4,"banco_de_altura, equipo_de_computo, lampara_de..."
3,CAMPECHE,CCIMB000930,CENTRO DE SALUD CARMEN,2,2,"lavabo, otoscopio"
4,CAMPECHE,CCIMB000930,CENTRO DE SALUD CARMEN,5,3,"banco_de_altura, guarda_de_medicamentos_materi..."
...,...,...,...,...,...,...
350,ZACATECAS,ZSIMB000434,CENTRO DE SALUD COL. TIERRA Y LIBERTAD,1,2,"carta_snellen_con_marco, estetoscopio_pinard_o..."
351,ZACATECAS,ZSIMB001402,CENTRO DE SALUD SANTA LUCÍA DE LA SIERRA,1,1,banco_giratorio
352,ZACATECAS,ZSIMB001641,CENTRO DE SALUD ZACATECAS,2,1,estadimetro_pediatrico
353,ZACATECAS,ZSIMB001641,CENTRO DE SALUD ZACATECAS,4,1,banco_giratorio
354,ZACATECAS,ZSIMB001641,CENTRO DE SALUD ZACATECAS,6,1,espejo_vestidor

In [515]:
# Exportar tabla de faltantes agrupados a public/faltantes.json
faltantes_path = output_dir / "faltantes.json"
faltantes_path.write_text(
    json.dumps(_clean_json(faltantes_90_agrupado), ensure_ascii=False, indent=2),
    encoding="utf-8",
)
print(f"Archivo generado: {faltantes_path}  ({len(faltantes_90_agrupado)} filas)")

Archivo generado: c:\Users\jose.valdez\Downloads\repor-arm\reporte-_angeles\public\faltantes.json  (355 filas)

In [517]:
# Unidades con MAYOR cobertura por entidad (top 1 por estado)
# Usando resumen_llenado_clues que tiene porcentaje_llenado_total
top_por_entidad = (
    resumen_llenado_clues
    .sort_values("porcentaje_llenado_total", ascending=False)
    .groupby("entidad", as_index=False)
    .first()[["entidad", "clues_imb", "nombre_de_la_unidad", "consultorios_reportados", "porcentaje_llenado_total"]]
    .sort_values("entidad")
    .reset_index(drop=True)
)

print(f"Entidades representadas: {len(top_por_entidad)}")
display(top_por_entidad.style.background_gradient(
    subset=["porcentaje_llenado_total"], cmap="RdYlGn", vmin=90, vmax=100
))

Entidades representadas: 19

In [518]:
# Todas las unidades de San Luis Potosí
slp = (
    resumen_llenado_clues[resumen_llenado_clues["entidad"].str.upper().str.contains("SAN LUIS")]
    [["clues_imb", "nombre_de_la_unidad", "consultorios_reportados",
      "preguntas_respondidas_validas_total", "preguntas_esperadas_total",
      "faltantes_total", "porcentaje_llenado_total"]]
    .sort_values("porcentaje_llenado_total", ascending=False)
    .reset_index(drop=True)
)

print(f"Unidades SLP con >=90%: {len(slp)}")
print(f"Promedio llenado: {slp['porcentaje_llenado_total'].mean():.1f}%")
print(f"Consultorios reportados total: {slp['consultorios_reportados'].sum()}")
display(slp)

Unidades SLP con >=90%: 27
Promedio llenado: 91.1%
Consultorios reportados total: 60

,clues_imb,nombre_de_la_unidad,consultorios_reportados,preguntas_respondidas_validas_total,preguntas_esperadas_total,faltantes_total,porcentaje_llenado_total
0,SPIMB000252,PIMIENTA,1,44,44,0,100.0
1,SPIMB000264,COL. JUÁREZ,2,88,88,0,100.0
2,SPIMB000696,SAUCITO,1,44,44,0,100.0
3,SPIMB001331,NUEVO TAMPAON,1,44,44,0,100.0
4,SPIMB000520,CENTRO DE SALUD LOS POCITOS,1,44,44,0,100.0
5,SPIMB000993,PONCIANO ARRIAGA,1,44,44,0,100.0
6,SPIMB000981,CENTRO DE SALUD 1RO. DE MAYO,2,88,88,0,100.0
7,SPIMB002340,CENTRO DE SALUD FRANCISCO VILLA,1,44,44,0,100.0
8,SPIMB002195,CENTRO DE SALUD 6 DE JUNIO,2,88,88,0,100.0
9,SPIMB002101,16 DE SEPTIEMBRE,2,88,88,0,100.0
10,SPIMB001442,LOS LOBOS,1,44,44,0,100.0
11,SPIMB002830,C.S. URBANO ANÁHUAC,1,44,44,0,100.0
12,SPIMB002760,SAN RAFAEL,1,44,44,0,100.0
13,SPIMB002731,CENTRO DE SALUD LOS MAGUEYES,2,88,88,0,100.0
14,SPIMB002545,CENTRO DE SALUD SAN ANTONIO,1,44,44,0,100.0
15,SPIMB002533,CENTRO DE SALUD BOSQUES DE JACARANDAS,2,88,88,0,100.0
16,SPIMB002521,CENTRO DE SALUD SIMÓN DÍAZ,1,44,44,0,100.0
17,SPIMB003146,CENTRO DE SALUD VILLA CACTUS,4,175,176,1,99.4
18,SPIMB002562,CENTRO DE SALUD TERCERAS,4,175,176,1,99.4
19,SPIMB002661,CENTRO DE SALUD JARDINES DE MARIA CECILIA,3,131,132,1,99.2
20,SPIMB000450,PONCIANO ARRIAGA,2,87,88,1,98.9
21,SPIMB000445,AURELIO MANRIQUE,1,43,44,1,97.7
22,SPIMB002842,UMF SOLEDAD DE GRACIANO SÁNCHEZ,5,192,220,28,87.3
23,SPIMB000433,PLAN DE IGUALA,1,31,44,13,70.5
24,SPIMB002241,CENTRO DE SALUD DORACELI,3,71,132,61,53.8
25,SPIMB002253,CENTRO DE SALUD ROTARIOS,3,40,132,92,30.3
26,SPIMB000701,DR. JUAN H. SANCHEZ,11,107,484,377,22.1